/* Code generated by quasar. DO NOT EDIT. */
#ifndef QUASAR_ESCROW_CLIENT_H
#define QUASAR_ESCROW_CLIENT_H

#include <caravel.h>

static const Pubkey QUASAR_ESCROW_PROGRAM_ID = {{
    0x0f, 0x1e, 0x6b, 0x14, 0x21, 0xc0, 0x4a, 0x07,
    0x04, 0x31, 0x26, 0x5c, 0x19, 0xc5, 0xbb, 0xee,
    0x19, 0x92, 0xba, 0xe8, 0xaf, 0xd1, 0xcd, 0x07,
    0x8e, 0xf8, 0xaf, 0x70, 0x47, 0xdc, 0x11, 0xf7
}};

static const Pubkey QUASAR_ESCROW_MAKE_RENT_ID = {{
    0x06, 0xa7, 0xd5, 0x17, 0x19, 0x2c, 0x5c, 0x51,
    0x21, 0x8c, 0xc9, 0x4c, 0x3d, 0x4a, 0xf1, 0x7f,
    0x58, 0xda, 0xee, 0x08, 0x9b, 0xa1, 0xfd, 0x44,
    0xe3, 0xdb, 0xd9, 0x8a, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_ESCROW_MAKE_TOKEN_PROGRAM_ID = {{
    0x06, 0xdd, 0xf6, 0xe1, 0xd7, 0x65, 0xa1, 0x93,
    0xd9, 0xcb, 0xe1, 0x46, 0xce, 0xeb, 0x79, 0xac,
    0x1c, 0xb4, 0x85, 0xed, 0x5f, 0x5b, 0x37, 0x91,
    0x3a, 0x8c, 0xf5, 0x85, 0x7e, 0xff, 0x00, 0xa9
}};

static const Pubkey QUASAR_ESCROW_MAKE_SYSTEM_PROGRAM_ID = {{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_ESCROW_TAKE_RENT_ID = {{
    0x06, 0xa7, 0xd5, 0x17, 0x19, 0x2c, 0x5c, 0x51,
    0x21, 0x8c, 0xc9, 0x4c, 0x3d, 0x4a, 0xf1, 0x7f,
    0x58, 0xda, 0xee, 0x08, 0x9b, 0xa1, 0xfd, 0x44,
    0xe3, 0xdb, 0xd9, 0x8a, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_ESCROW_TAKE_TOKEN_PROGRAM_ID = {{
    0x06, 0xdd, 0xf6, 0xe1, 0xd7, 0x65, 0xa1, 0x93,
    0xd9, 0xcb, 0xe1, 0x46, 0xce, 0xeb, 0x79, 0xac,
    0x1c, 0xb4, 0x85, 0xed, 0x5f, 0x5b, 0x37, 0x91,
    0x3a, 0x8c, 0xf5, 0x85, 0x7e, 0xff, 0x00, 0xa9
}};

static const Pubkey QUASAR_ESCROW_TAKE_SYSTEM_PROGRAM_ID = {{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_ESCROW_REFUND_RENT_ID = {{
    0x06, 0xa7, 0xd5, 0x17, 0x19, 0x2c, 0x5c, 0x51,
    0x21, 0x8c, 0xc9, 0x4c, 0x3d, 0x4a, 0xf1, 0x7f,
    0x58, 0xda, 0xee, 0x08, 0x9b, 0xa1, 0xfd, 0x44,
    0xe3, 0xdb, 0xd9, 0x8a, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_ESCROW_REFUND_TOKEN_PROGRAM_ID = {{
    0x06, 0xdd, 0xf6, 0xe1, 0xd7, 0x65, 0xa1, 0x93,
    0xd9, 0xcb, 0xe1, 0x46, 0xce, 0xeb, 0x79, 0xac,
    0x1c, 0xb4, 0x85, 0xed, 0x5f, 0x5b, 0x37, 0x91,
    0x3a, 0x8c, 0xf5, 0x85, 0x7e, 0xff, 0x00, 0xa9
}};

static const Pubkey QUASAR_ESCROW_REFUND_SYSTEM_PROGRAM_ID = {{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}};

static const uint8_t QUASAR_ESCROW_MAKE_DISC[] = {0x00};
static const uint8_t QUASAR_ESCROW_TAKE_DISC[] = {0x01};
static const uint8_t QUASAR_ESCROW_REFUND_DISC[] = {0x02};

static const uint8_t QUASAR_ESCROW_ESCROW_ACCOUNT_DISC[] = {0x01};

static const uint8_t QUASAR_ESCROW_MAKE_EVENT_EVENT_DISC[] = {0x01};
static const uint8_t QUASAR_ESCROW_REFUND_EVENT_EVENT_DISC[] = {0x03};
static const uint8_t QUASAR_ESCROW_TAKE_EVENT_EVENT_DISC[] = {0x02};

typedef struct {
    const uint8_t *data;
    uint64_t len;
    uint64_t offset;
} quasar_escrow_decoder_t;

static inline bool quasar_escrow_decoder_take(
    quasar_escrow_decoder_t *decoder,
    uint64_t size,
    const uint8_t **value
) {
    if (size > decoder->len - decoder->offset) return false;
    *value = &decoder->data[decoder->offset];
    decoder->offset += size;
    return true;
}

static inline bool quasar_escrow_decoder_uint(
    quasar_escrow_decoder_t *decoder,
    uint8_t width,
    uint64_t *value
) {
    const uint8_t *bytes;
    if (width != 1 && width != 2 && width != 4 && width != 8) return false;
    if (!quasar_escrow_decoder_take(decoder, width, &bytes)) return false;
    *value = 0;
    for (uint8_t i = 0; i < width; i++) *value |= ((uint64_t)bytes[i]) << (i * 8);
    return true;
}

static inline bool quasar_escrow_decoder_span(
    quasar_escrow_decoder_t *decoder,
    uint8_t width,
    uint32_t item_size,
    const uint8_t **value,
    uint32_t *count
) {
    uint64_t count64;
    if (!quasar_escrow_decoder_uint(decoder, width, &count64)) return false;
    if (count64 > ((uint32_t)-1)) return false;
    uint64_t byte_len = count64 * item_size;
    if (!quasar_escrow_decoder_take(decoder, byte_len, value)) return false;
    *count = (uint32_t)count64;
    return true;
}

static inline bool quasar_escrow_utf8_valid(const uint8_t *data, uint32_t len) {
    uint32_t i = 0;
    while (i < len) {
        uint8_t c = data[i++];
        if (c < 0x80) continue;
        uint32_t needed;
        uint32_t code;
        uint32_t minimum;
        if ((c & 0xe0) == 0xc0) { needed = 1; code = c & 0x1f; minimum = 0x80; }
        else if ((c & 0xf0) == 0xe0) { needed = 2; code = c & 0x0f; minimum = 0x800; }
        else if ((c & 0xf8) == 0xf0) { needed = 3; code = c & 0x07; minimum = 0x10000; }
        else return false;
        if (needed > len - i) return false;
        for (uint32_t j = 0; j < needed; j++) {
            uint8_t next = data[i++];
            if ((next & 0xc0) != 0x80) return false;
            code = (code << 6) | (next & 0x3f);
        }
        if (code < minimum || code > 0x10ffff || (code >= 0xd800 && code <= 0xdfff)) return false;
    }
    return true;
}

typedef struct {
    Pubkey maker;
    Pubkey mint_a;
    Pubkey mint_b;
    Pubkey maker_ta_b;
    uint64_t receive;
    uint8_t bump;
} quasar_escrow_escrow_t;

typedef struct {
    Pubkey escrow;
    Pubkey maker;
    Pubkey mint_a;
    Pubkey mint_b;
    uint64_t deposit;
    uint64_t receive;
} quasar_escrow_make_event_t;

typedef struct {
    Pubkey escrow;
} quasar_escrow_refund_event_t;

typedef struct {
    Pubkey escrow;
} quasar_escrow_take_event_t;

static inline bool quasar_escrow_escrow_decode(
    const uint8_t *data,
    uint64_t data_len,
    quasar_escrow_escrow_t *out
) {
    quasar_escrow_decoder_t decoder = { .data = data, .len = data_len, .offset = 0 };
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->maker.bytes[i] = bytes[i]; }
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->mint_a.bytes[i] = bytes[i]; }
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->mint_b.bytes[i] = bytes[i]; }
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->maker_ta_b.bytes[i] = bytes[i]; }
    { uint64_t v; if (!quasar_escrow_decoder_uint(&decoder, 8, &v)) return false; out->receive = v; }
    { uint64_t v; if (!quasar_escrow_decoder_uint(&decoder, 1, &v)) return false; out->bump = (uint8_t)v; }
    return decoder.offset == decoder.len;
}

static inline bool quasar_escrow_make_event_decode(
    const uint8_t *data,
    uint64_t data_len,
    quasar_escrow_make_event_t *out
) {
    quasar_escrow_decoder_t decoder = { .data = data, .len = data_len, .offset = 0 };
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->escrow.bytes[i] = bytes[i]; }
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->maker.bytes[i] = bytes[i]; }
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->mint_a.bytes[i] = bytes[i]; }
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->mint_b.bytes[i] = bytes[i]; }
    { uint64_t v; if (!quasar_escrow_decoder_uint(&decoder, 8, &v)) return false; out->deposit = v; }
    { uint64_t v; if (!quasar_escrow_decoder_uint(&decoder, 8, &v)) return false; out->receive = v; }
    return decoder.offset == decoder.len;
}

static inline bool quasar_escrow_refund_event_decode(
    const uint8_t *data,
    uint64_t data_len,
    quasar_escrow_refund_event_t *out
) {
    quasar_escrow_decoder_t decoder = { .data = data, .len = data_len, .offset = 0 };
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->escrow.bytes[i] = bytes[i]; }
    return decoder.offset == decoder.len;
}

static inline bool quasar_escrow_take_event_decode(
    const uint8_t *data,
    uint64_t data_len,
    quasar_escrow_take_event_t *out
) {
    quasar_escrow_decoder_t decoder = { .data = data, .len = data_len, .offset = 0 };
    { const uint8_t *bytes; if (!quasar_escrow_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->escrow.bytes[i] = bytes[i]; }
    return decoder.offset == decoder.len;
}

typedef enum {
    QUASAR_ESCROW_IX_OK = 0,
    QUASAR_ESCROW_IX_ACCOUNT_BUFFER_TOO_SMALL,
    QUASAR_ESCROW_IX_DATA_BUFFER_TOO_SMALL,
    QUASAR_ESCROW_IX_LENGTH_OVERFLOW,
    QUASAR_ESCROW_IX_PDA_DERIVATION_FAILED,
    QUASAR_ESCROW_IX_PDA_KEY_BUFFER_TOO_SMALL
} quasar_escrow_ix_status_t;

typedef struct {
    quasar_escrow_ix_status_t status;
    uint64_t accounts_len;
    uint64_t data_len;
    uint64_t pda_keys_len;
    uint64_t pda_status;
} quasar_escrow_ix_result_t;

static inline bool quasar_escrow_ix_size_add(uint64_t *size, uint64_t amount) {
    if (amount > ((uint64_t)-1) - *size) return false;
    *size += amount;
    return true;
}

static inline bool quasar_escrow_ix_size_add_items(
    uint64_t *size,
    uint64_t count,
    uint64_t item_size
) {
    if (item_size != 0 && count > ((uint64_t)-1) / item_size) return false;
    return quasar_escrow_ix_size_add(size, count * item_size);
}

typedef struct {
    Pubkey *maker;
    Pubkey *mintA;
    Pubkey *mintB;
    Pubkey *makerTaA;
    Pubkey *makerTaB;
    Pubkey *vaultTaA;
} quasar_escrow_make_accounts_t;

typedef struct {
    uint64_t deposit;
    uint64_t receive;
} quasar_escrow_make_args_t;

static inline quasar_escrow_ix_result_t quasar_escrow_make_ix(
    quasar_escrow_make_accounts_t *accounts,
    quasar_escrow_make_args_t *args,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint64_t meta_buf_capacity,
    Pubkey *pda_key_buf,
    uint64_t pda_key_buf_capacity,
    uint8_t *data_buf,
    uint64_t data_buf_capacity
) {
    const uint64_t required_pda_keys = 1;
    uint64_t required_accounts = 10;
    uint64_t required_data = 1;
    if (!quasar_escrow_ix_size_add(&required_data, 8)) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (!quasar_escrow_ix_size_add(&required_data, 8)) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (meta_buf_capacity < required_accounts) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (pda_key_buf_capacity < required_pda_keys) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_PDA_KEY_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (data_buf_capacity < required_data) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    Pubkey derived_pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}; seeds[0].addr = s; seeds[0].len = 6; }
        seeds[1].addr = accounts->maker->bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_ESCROW_PROGRAM_ID, &derived_pda_keys[0], &bump);
        if (pda_status != SUCCESS) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = derived_pda_keys[i];
    meta_buf[0] = meta_writable_signer(accounts->maker);
    meta_buf[1] = meta_writable(&pda_key_buf[0]);
    meta_buf[2] = meta_readonly(accounts->mintA);
    meta_buf[3] = meta_readonly(accounts->mintB);
    meta_buf[4] = meta_writable(accounts->makerTaA);
    meta_buf[5] = meta_writable_signer(accounts->makerTaB);
    meta_buf[6] = meta_writable_signer(accounts->vaultTaA);
    meta_buf[7] = meta_readonly((Pubkey *)&QUASAR_ESCROW_MAKE_RENT_ID);
    meta_buf[8] = meta_readonly((Pubkey *)&QUASAR_ESCROW_MAKE_TOKEN_PROGRAM_ID);
    meta_buf[9] = meta_readonly((Pubkey *)&QUASAR_ESCROW_MAKE_SYSTEM_PROGRAM_ID);
    uint64_t off = 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_ESCROW_MAKE_DISC[i];
    { uint64_t v = args->deposit; for (int i = 0; i < 8; i++) { data_buf[off + i] = (uint8_t)(v >> (i * 8)); } off += 8; }
    { uint64_t v = args->receive; for (int i = 0; i < 8; i++) { data_buf[off + i] = (uint8_t)(v >> (i * 8)); } off += 8; }
    ix_out->program_id = (Pubkey *)&QUASAR_ESCROW_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = required_accounts;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_OK, .accounts_len = required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
}

typedef struct {
    Pubkey *taker;
    Pubkey *maker;
    Pubkey *mintA;
    Pubkey *mintB;
    Pubkey *takerTaA;
    Pubkey *takerTaB;
    Pubkey *makerTaB;
    Pubkey *vaultTaA;
} quasar_escrow_take_accounts_t;

typedef struct {
    uint8_t _pad;
} quasar_escrow_take_args_t;

static inline quasar_escrow_ix_result_t quasar_escrow_take_ix(
    quasar_escrow_take_accounts_t *accounts,
    quasar_escrow_take_args_t *args,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint64_t meta_buf_capacity,
    Pubkey *pda_key_buf,
    uint64_t pda_key_buf_capacity,
    uint8_t *data_buf,
    uint64_t data_buf_capacity
) {
    (void)args;
    const uint64_t required_pda_keys = 1;
    uint64_t required_accounts = 12;
    uint64_t required_data = 1;
    if (meta_buf_capacity < required_accounts) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (pda_key_buf_capacity < required_pda_keys) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_PDA_KEY_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (data_buf_capacity < required_data) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    Pubkey derived_pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}; seeds[0].addr = s; seeds[0].len = 6; }
        seeds[1].addr = accounts->maker->bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_ESCROW_PROGRAM_ID, &derived_pda_keys[0], &bump);
        if (pda_status != SUCCESS) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = derived_pda_keys[i];
    meta_buf[0] = meta_writable_signer(accounts->taker);
    meta_buf[1] = meta_writable(&pda_key_buf[0]);
    meta_buf[2] = meta_writable(accounts->maker);
    meta_buf[3] = meta_readonly(accounts->mintA);
    meta_buf[4] = meta_readonly(accounts->mintB);
    meta_buf[5] = meta_writable_signer(accounts->takerTaA);
    meta_buf[6] = meta_writable(accounts->takerTaB);
    meta_buf[7] = meta_writable_signer(accounts->makerTaB);
    meta_buf[8] = meta_writable(accounts->vaultTaA);
    meta_buf[9] = meta_readonly((Pubkey *)&QUASAR_ESCROW_TAKE_RENT_ID);
    meta_buf[10] = meta_readonly((Pubkey *)&QUASAR_ESCROW_TAKE_TOKEN_PROGRAM_ID);
    meta_buf[11] = meta_readonly((Pubkey *)&QUASAR_ESCROW_TAKE_SYSTEM_PROGRAM_ID);
    uint64_t off = 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_ESCROW_TAKE_DISC[i];
    ix_out->program_id = (Pubkey *)&QUASAR_ESCROW_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = required_accounts;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_OK, .accounts_len = required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
}

typedef struct {
    Pubkey *maker;
    Pubkey *mintA;
    Pubkey *makerTaA;
    Pubkey *vaultTaA;
} quasar_escrow_refund_accounts_t;

typedef struct {
    uint8_t _pad;
} quasar_escrow_refund_args_t;

static inline quasar_escrow_ix_result_t quasar_escrow_refund_ix(
    quasar_escrow_refund_accounts_t *accounts,
    quasar_escrow_refund_args_t *args,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint64_t meta_buf_capacity,
    Pubkey *pda_key_buf,
    uint64_t pda_key_buf_capacity,
    uint8_t *data_buf,
    uint64_t data_buf_capacity
) {
    (void)args;
    const uint64_t required_pda_keys = 1;
    uint64_t required_accounts = 8;
    uint64_t required_data = 1;
    if (meta_buf_capacity < required_accounts) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (pda_key_buf_capacity < required_pda_keys) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_PDA_KEY_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (data_buf_capacity < required_data) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    Pubkey derived_pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}; seeds[0].addr = s; seeds[0].len = 6; }
        seeds[1].addr = accounts->maker->bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_ESCROW_PROGRAM_ID, &derived_pda_keys[0], &bump);
        if (pda_status != SUCCESS) return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = derived_pda_keys[i];
    meta_buf[0] = meta_writable_signer(accounts->maker);
    meta_buf[1] = meta_writable(&pda_key_buf[0]);
    meta_buf[2] = meta_readonly(accounts->mintA);
    meta_buf[3] = meta_writable_signer(accounts->makerTaA);
    meta_buf[4] = meta_writable(accounts->vaultTaA);
    meta_buf[5] = meta_readonly((Pubkey *)&QUASAR_ESCROW_REFUND_RENT_ID);
    meta_buf[6] = meta_readonly((Pubkey *)&QUASAR_ESCROW_REFUND_TOKEN_PROGRAM_ID);
    meta_buf[7] = meta_readonly((Pubkey *)&QUASAR_ESCROW_REFUND_SYSTEM_PROGRAM_ID);
    uint64_t off = 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_ESCROW_REFUND_DISC[i];
    ix_out->program_id = (Pubkey *)&QUASAR_ESCROW_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = required_accounts;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return (quasar_escrow_ix_result_t){ .status = QUASAR_ESCROW_IX_OK, .accounts_len = required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
}

#define QUASAR_ESCROW_ERR_ACCOUNTALREADYINITIALIZED 3001
#define QUASAR_ESCROW_ERR_ACCOUNTNOTINITIALIZED 3000
#define QUASAR_ESCROW_ERR_ACCOUNTNOTMUTABLE 3010
#define QUASAR_ESCROW_ERR_ACCOUNTNOTRENTEXEMPT 3008
#define QUASAR_ESCROW_ERR_ACCOUNTNOTSIGNER 3011
#define QUASAR_ESCROW_ERR_ACCOUNTOWNEDBYWRONGPROGRAM 3009
#define QUASAR_ESCROW_ERR_ADDRESSMISMATCH 3012
#define QUASAR_ESCROW_ERR_COMPACTWRITERFIELDNOTSET 3014
#define QUASAR_ESCROW_ERR_CONSTRAINTVIOLATION 3004
#define QUASAR_ESCROW_ERR_DYNAMICFIELDTOOLONG 3013
#define QUASAR_ESCROW_ERR_HASONEMISMATCH 3005
#define QUASAR_ESCROW_ERR_INSUFFICIENTSPACE 3007
#define QUASAR_ESCROW_ERR_INVALIDDISCRIMINATOR 3006
#define QUASAR_ESCROW_ERR_INVALIDPDA 3002
#define QUASAR_ESCROW_ERR_INVALIDRETURNDATA 3019
#define QUASAR_ESCROW_ERR_INVALIDSEEDS 3003
#define QUASAR_ESCROW_ERR_MISSINGRETURNDATA 3017
#define QUASAR_ESCROW_ERR_REMAININGACCOUNTDUPLICATE 3016
#define QUASAR_ESCROW_ERR_REMAININGACCOUNTSOVERFLOW 3015
#define QUASAR_ESCROW_ERR_RETURNDATAFROMWRONGPROGRAM 3018

#endif /* QUASAR_ESCROW_CLIENT_H */
