// Code generated by quasar. DO NOT EDIT.
package quasar_escrow

import (
	"errors"
	"encoding/binary"
	"bytes"
	"unicode/utf8"

	solana "github.com/gagliardetto/solana-go"
)

var ProgramID = solana.MustPublicKeyFromBase58("22222222222222222222222222222222222222222222")

const maxDecodeElements = 10 * 1024 * 1024

type quasarDecoder struct {
	data []byte
	offset int
	err error
}

func (d *quasarDecoder) fail(message string) {
	if d.err == nil { d.err = errors.New(message) }
}

func (d *quasarDecoder) take(size int) []byte {
	if d.err != nil { return nil }
	if size < 0 || d.offset < 0 || size > len(d.data)-d.offset {
		d.fail("truncated input")
		return nil
	}
	end := d.offset + size
	value := d.data[d.offset:end]
	d.offset = end
	return value
}

func (d *quasarDecoder) length(width int) int {
	raw := d.take(width)
	if d.err != nil { return 0 }
	var value uint64
	switch width {
	case 1: value = uint64(raw[0])
	case 2: value = uint64(binary.LittleEndian.Uint16(raw))
	case 4: value = uint64(binary.LittleEndian.Uint32(raw))
	case 8: value = binary.LittleEndian.Uint64(raw)
	default: d.fail("invalid length prefix width"); return 0
	}
	if value > uint64(^uint(0)>>1) { d.fail("length overflows int"); return 0 }
	return int(value)
}

func (d *quasarDecoder) u8() uint8 {
	raw := d.take(1); if d.err != nil { return 0 }; return raw[0]
}

func (d *quasarDecoder) u16() uint16 {
	raw := d.take(2); if d.err != nil { return 0 }; return binary.LittleEndian.Uint16(raw)
}

func (d *quasarDecoder) u32() uint32 {
	raw := d.take(4); if d.err != nil { return 0 }; return binary.LittleEndian.Uint32(raw)
}

func (d *quasarDecoder) u64() uint64 {
	raw := d.take(8); if d.err != nil { return 0 }; return binary.LittleEndian.Uint64(raw)
}

func (d *quasarDecoder) elements(width int) int {
	count := d.length(width)
	if count > maxDecodeElements || count > len(d.data)-d.offset { d.fail("element count exceeds limit"); return 0 }
	return count
}

func (d *quasarDecoder) bool() bool {
	raw := d.u8()
	if d.err != nil { return false }
	if raw > 1 { d.fail("invalid bool"); return false }
	return raw == 1
}

func (d *quasarDecoder) string(size int) string {
	raw := d.take(size)
	if d.err != nil { return "" }
	if !utf8.Valid(raw) { d.fail("invalid UTF-8"); return "" }
	return string(raw)
}

func (d *quasarDecoder) finish() error {
	if d.err != nil { return d.err }
	if d.offset != len(d.data) { return errors.New("trailing bytes") }
	return nil
}

var MakeDiscriminator = [1]byte{0x00}
var TakeDiscriminator = [1]byte{0x01}
var RefundDiscriminator = [1]byte{0x02}

var EscrowAccountDiscriminator = [1]byte{0x01}

var MakeEventEventDiscriminator = [1]byte{0x01}
var RefundEventEventDiscriminator = [1]byte{0x03}
var TakeEventEventDiscriminator = [1]byte{0x02}

type Escrow struct {
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	MakerTaB solana.PublicKey
	Receive uint64
	Bump uint8
}

func DecodeEscrow(data []byte) (*Escrow, error) {
	decoder := quasarDecoder{data: data}
	var maker solana.PublicKey
	copy(maker[:], decoder.take(32))
	var mintA solana.PublicKey
	copy(mintA[:], decoder.take(32))
	var mintB solana.PublicKey
	copy(mintB[:], decoder.take(32))
	var makerTaB solana.PublicKey
	copy(makerTaB[:], decoder.take(32))
	receive := decoder.u64()
	bump := decoder.u8()
	if err := decoder.finish(); err != nil { return nil, err }
	return &Escrow {
		Maker: maker,
		MintA: mintA,
		MintB: mintB,
		MakerTaB: makerTaB,
		Receive: receive,
		Bump: bump,
	}, nil
}

type MakeEvent struct {
	Escrow solana.PublicKey
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	Deposit uint64
	Receive uint64
}

func DecodeMakeEvent(data []byte) (*MakeEvent, error) {
	decoder := quasarDecoder{data: data}
	var escrow solana.PublicKey
	copy(escrow[:], decoder.take(32))
	var maker solana.PublicKey
	copy(maker[:], decoder.take(32))
	var mintA solana.PublicKey
	copy(mintA[:], decoder.take(32))
	var mintB solana.PublicKey
	copy(mintB[:], decoder.take(32))
	deposit := decoder.u64()
	receive := decoder.u64()
	if err := decoder.finish(); err != nil { return nil, err }
	return &MakeEvent {
		Escrow: escrow,
		Maker: maker,
		MintA: mintA,
		MintB: mintB,
		Deposit: deposit,
		Receive: receive,
	}, nil
}

type RefundEvent struct {
	Escrow solana.PublicKey
}

func DecodeRefundEvent(data []byte) (*RefundEvent, error) {
	decoder := quasarDecoder{data: data}
	var escrow solana.PublicKey
	copy(escrow[:], decoder.take(32))
	if err := decoder.finish(); err != nil { return nil, err }
	return &RefundEvent {
		Escrow: escrow,
	}, nil
}

type TakeEvent struct {
	Escrow solana.PublicKey
}

func DecodeTakeEvent(data []byte) (*TakeEvent, error) {
	decoder := quasarDecoder{data: data}
	var escrow solana.PublicKey
	copy(escrow[:], decoder.take(32))
	if err := decoder.finish(); err != nil { return nil, err }
	return &TakeEvent {
		Escrow: escrow,
	}, nil
}

type MakeInput struct {
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	MakerTaA solana.PublicKey
	MakerTaB solana.PublicKey
	VaultTaA solana.PublicKey
	Deposit uint64
	Receive uint64
}

func NewMakeInstruction(input *MakeInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{}
	accountsMap := map[string]solana.PublicKey{}
	accountsMap["maker"] = input.Maker
	accountsMap["mintA"] = input.MintA
	accountsMap["mintB"] = input.MintB
	accountsMap["makerTaA"] = input.MakerTaA
	accountsMap["makerTaB"] = input.MakerTaB
	accountsMap["vaultTaA"] = input.VaultTaA
	accountsMap["rent"] = solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")
	accountsMap["tokenProgram"] = solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	accountsMap["systemProgram"] = solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	accountsMap["escrow"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}, func() []byte { key := accountsMap["maker"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["maker"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["escrow"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["mintA"]))
	accounts = append(accounts, solana.Meta(accountsMap["mintB"]))
	accounts = append(accounts, solana.Meta(accountsMap["makerTaA"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["makerTaB"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["vaultTaA"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["rent"]))
	accounts = append(accounts, solana.Meta(accountsMap["tokenProgram"]))
	accounts = append(accounts, solana.Meta(accountsMap["systemProgram"]))
	data := make([]byte, 0, 256)
	data = append(data, MakeDiscriminator[:]...)
	{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.Deposit); data = append(data, buf[:]...) }
	{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.Receive); data = append(data, buf[:]...) }
	return solana.NewInstruction(ProgramID, accounts, data)
}

type TakeInput struct {
	Taker solana.PublicKey
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	TakerTaA solana.PublicKey
	TakerTaB solana.PublicKey
	MakerTaB solana.PublicKey
	VaultTaA solana.PublicKey
}

func NewTakeInstruction(input *TakeInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{}
	accountsMap := map[string]solana.PublicKey{}
	accountsMap["taker"] = input.Taker
	accountsMap["maker"] = input.Maker
	accountsMap["mintA"] = input.MintA
	accountsMap["mintB"] = input.MintB
	accountsMap["takerTaA"] = input.TakerTaA
	accountsMap["takerTaB"] = input.TakerTaB
	accountsMap["makerTaB"] = input.MakerTaB
	accountsMap["vaultTaA"] = input.VaultTaA
	accountsMap["rent"] = solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")
	accountsMap["tokenProgram"] = solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	accountsMap["systemProgram"] = solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	accountsMap["escrow"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}, func() []byte { key := accountsMap["maker"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["taker"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["escrow"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["maker"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["mintA"]))
	accounts = append(accounts, solana.Meta(accountsMap["mintB"]))
	accounts = append(accounts, solana.Meta(accountsMap["takerTaA"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["takerTaB"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["makerTaB"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["vaultTaA"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["rent"]))
	accounts = append(accounts, solana.Meta(accountsMap["tokenProgram"]))
	accounts = append(accounts, solana.Meta(accountsMap["systemProgram"]))
	data := TakeDiscriminator[:]
	return solana.NewInstruction(ProgramID, accounts, data)
}

type RefundInput struct {
	Maker solana.PublicKey
	MintA solana.PublicKey
	MakerTaA solana.PublicKey
	VaultTaA solana.PublicKey
}

func NewRefundInstruction(input *RefundInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{}
	accountsMap := map[string]solana.PublicKey{}
	accountsMap["maker"] = input.Maker
	accountsMap["mintA"] = input.MintA
	accountsMap["makerTaA"] = input.MakerTaA
	accountsMap["vaultTaA"] = input.VaultTaA
	accountsMap["rent"] = solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")
	accountsMap["tokenProgram"] = solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	accountsMap["systemProgram"] = solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	accountsMap["escrow"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}, func() []byte { key := accountsMap["maker"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["maker"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["escrow"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["mintA"]))
	accounts = append(accounts, solana.Meta(accountsMap["makerTaA"]).WRITE().SIGNER())
	accounts = append(accounts, solana.Meta(accountsMap["vaultTaA"]).WRITE())
	accounts = append(accounts, solana.Meta(accountsMap["rent"]))
	accounts = append(accounts, solana.Meta(accountsMap["tokenProgram"]))
	accounts = append(accounts, solana.Meta(accountsMap["systemProgram"]))
	data := RefundDiscriminator[:]
	return solana.NewInstruction(ProgramID, accounts, data)
}

type DecodedEvent struct {
	Name string
	Data interface{}
}

func DecodeEvent(data []byte) (*DecodedEvent, error) {
	if len(data) >= 1 && bytes.Equal(data[:1], MakeEventEventDiscriminator[:]) {
		value, err := DecodeMakeEvent(data[1:])
		if err != nil { return nil, err }
		return &DecodedEvent{Name: "MakeEvent", Data: value}, nil
	}
	if len(data) >= 1 && bytes.Equal(data[:1], RefundEventEventDiscriminator[:]) {
		value, err := DecodeRefundEvent(data[1:])
		if err != nil { return nil, err }
		return &DecodedEvent{Name: "RefundEvent", Data: value}, nil
	}
	if len(data) >= 1 && bytes.Equal(data[:1], TakeEventEventDiscriminator[:]) {
		value, err := DecodeTakeEvent(data[1:])
		if err != nil { return nil, err }
		return &DecodedEvent{Name: "TakeEvent", Data: value}, nil
	}
	return nil, nil
}
