use {
    super::model::{reject_generics, validate_codegen_idl, CodegenResult},
    crate::types::{Idl, IdlCodec, IdlPdaSeed, IdlResolver, IdlType, IdlTypeDef},
    quasar_schema::pascal_to_snake,
    std::{collections::HashMap, fmt::Write},
};

/// Generate a C client header from the IDL.
///
/// Produces a single header depending on `caravel.h` for Pubkey, AccountMeta,
/// and Instruction.
pub fn generate_c_client(idl: &Idl) -> CodegenResult<String> {
    validate_codegen_idl(idl)?;
    reject_generics(idl, "C")?;
    let prefix = idl.metadata.client_name(&idl.name).replace('-', "_");
    let guard = format!("{}_CLIENT_H", prefix.to_ascii_uppercase());
    let mut out = String::new();

    writeln!(out, "/* Code generated by quasar. DO NOT EDIT. */").unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}\n").unwrap();
    writeln!(out, "#include <caravel.h>\n").unwrap();

    emit_program_id(&mut out, &prefix, &idl.address);
    emit_fixed_account_ids(&mut out, &prefix, idl);
    emit_discriminators(&mut out, &prefix, idl);
    emit_decoder_helpers(&mut out, &prefix);
    emit_type_defs(&mut out, &prefix, &idl.types);
    emit_decode_fns(&mut out, &prefix, &idl.types);
    emit_instruction_helpers(&mut out, &prefix, idl);
    emit_instructions(&mut out, &prefix, idl);
    emit_error_codes(&mut out, &prefix, &idl.errors);

    writeln!(out, "#endif /* {guard} */").unwrap();
    Ok(out)
}

fn emit_instruction_helpers(out: &mut String, prefix: &str, idl: &Idl) {
    if idl.instructions.is_empty() {
        return;
    }

    let upper = prefix.to_ascii_uppercase();
    writeln!(
        out,
        r#"typedef enum {{
    {upper}_IX_OK = 0,
    {upper}_IX_ACCOUNT_BUFFER_TOO_SMALL,
    {upper}_IX_DATA_BUFFER_TOO_SMALL,
    {upper}_IX_LENGTH_OVERFLOW,
    {upper}_IX_PDA_DERIVATION_FAILED,
    {upper}_IX_PDA_KEY_BUFFER_TOO_SMALL
}} {prefix}_ix_status_t;

typedef struct {{
    {prefix}_ix_status_t status;
    uint64_t accounts_len;
    uint64_t data_len;
    uint64_t pda_keys_len;
    uint64_t pda_status;
}} {prefix}_ix_result_t;

static inline bool {prefix}_ix_size_add(uint64_t *size, uint64_t amount) {{
    if (amount > ((uint64_t)-1) - *size) return false;
    *size += amount;
    return true;
}}

static inline bool {prefix}_ix_size_add_items(
    uint64_t *size,
    uint64_t count,
    uint64_t item_size
) {{
    if (item_size != 0 && count > ((uint64_t)-1) / item_size) return false;
    return {prefix}_ix_size_add(size, count * item_size);
}}
"#
    )
    .unwrap();
}

fn emit_decoder_helpers(out: &mut String, prefix: &str) {
    writeln!(
        out,
        r#"typedef struct {{
    const uint8_t *data;
    uint64_t len;
    uint64_t offset;
}} {prefix}_decoder_t;

static inline bool {prefix}_decoder_take(
    {prefix}_decoder_t *decoder,
    uint64_t size,
    const uint8_t **value
) {{
    if (size > decoder->len - decoder->offset) return false;
    *value = &decoder->data[decoder->offset];
    decoder->offset += size;
    return true;
}}

static inline bool {prefix}_decoder_uint(
    {prefix}_decoder_t *decoder,
    uint8_t width,
    uint64_t *value
) {{
    const uint8_t *bytes;
    if (width != 1 && width != 2 && width != 4 && width != 8) return false;
    if (!{prefix}_decoder_take(decoder, width, &bytes)) return false;
    *value = 0;
    for (uint8_t i = 0; i < width; i++) *value |= ((uint64_t)bytes[i]) << (i * 8);
    return true;
}}

static inline bool {prefix}_decoder_span(
    {prefix}_decoder_t *decoder,
    uint8_t width,
    uint32_t item_size,
    const uint8_t **value,
    uint32_t *count
) {{
    uint64_t count64;
    if (!{prefix}_decoder_uint(decoder, width, &count64)) return false;
    if (count64 > ((uint32_t)-1)) return false;
    uint64_t byte_len = count64 * item_size;
    if (!{prefix}_decoder_take(decoder, byte_len, value)) return false;
    *count = (uint32_t)count64;
    return true;
}}

static inline bool {prefix}_utf8_valid(const uint8_t *data, uint32_t len) {{
    uint32_t i = 0;
    while (i < len) {{
        uint8_t c = data[i++];
        if (c < 0x80) continue;
        uint32_t needed;
        uint32_t code;
        uint32_t minimum;
        if ((c & 0xe0) == 0xc0) {{ needed = 1; code = c & 0x1f; minimum = 0x80; }}
        else if ((c & 0xf0) == 0xe0) {{ needed = 2; code = c & 0x0f; minimum = 0x800; }}
        else if ((c & 0xf8) == 0xf0) {{ needed = 3; code = c & 0x07; minimum = 0x10000; }}
        else return false;
        if (needed > len - i) return false;
        for (uint32_t j = 0; j < needed; j++) {{
            uint8_t next = data[i++];
            if ((next & 0xc0) != 0x80) return false;
            code = (code << 6) | (next & 0x3f);
        }}
        if (code < minimum || code > 0x10ffff || (code >= 0xd800 && code <= 0xdfff)) return false;
    }}
    return true;
}}
"#
    )
    .unwrap();
}

fn emit_program_id(out: &mut String, prefix: &str, address: &str) {
    let upper = prefix.to_ascii_uppercase();
    emit_pubkey_const(out, &format!("{upper}_PROGRAM_ID"), address);
}

fn emit_fixed_account_ids(out: &mut String, prefix: &str, idl: &Idl) {
    for instruction in &idl.instructions {
        for account in &instruction.accounts {
            if account.optional {
                continue;
            }
            if let IdlResolver::Const { address } = &account.resolver {
                emit_pubkey_const(
                    out,
                    &fixed_account_id_name(prefix, &instruction.name, &account.name),
                    address,
                );
            }
        }
    }
}

fn fixed_account_id_name(prefix: &str, instruction: &str, account: &str) -> String {
    format!(
        "{}_{}_{}_ID",
        prefix.to_ascii_uppercase(),
        pascal_to_snake(instruction).to_ascii_uppercase(),
        pascal_to_snake(account).to_ascii_uppercase(),
    )
}

fn emit_pubkey_const(out: &mut String, name: &str, address: &str) {
    let bytes = bs58::decode(address).into_vec().unwrap_or_default();
    write!(out, "static const Pubkey {name} = {{{{").unwrap();
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}").unwrap();
    }
    out.push_str("\n}};\n\n");
}

fn emit_discriminators(out: &mut String, prefix: &str, idl: &Idl) {
    let upper = prefix.to_ascii_uppercase();

    for ix in &idl.instructions {
        let name = pascal_to_snake(&ix.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_DISC[] = {{{}}};",
            super::format_disc_hex(&ix.discriminator),
        )
        .unwrap();
    }
    if !idl.instructions.is_empty() {
        out.push('\n');
    }

    for acc in &idl.accounts {
        let name = pascal_to_snake(&acc.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_ACCOUNT_DISC[] = {{{}}};",
            super::format_disc_hex(&acc.discriminator),
        )
        .unwrap();
    }
    if !idl.accounts.is_empty() {
        out.push('\n');
    }

    for ev in &idl.events {
        let name = pascal_to_snake(&ev.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_EVENT_DISC[] = {{{}}};",
            super::format_disc_hex(&ev.discriminator),
        )
        .unwrap();
    }
    if !idl.events.is_empty() {
        out.push('\n');
    }
}

fn emit_type_defs(out: &mut String, prefix: &str, types: &[IdlTypeDef]) {
    for td in types {
        let snake = pascal_to_snake(&td.name);
        writeln!(out, "typedef struct {{").unwrap();
        if td.fields.is_empty() {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        for field in &td.fields {
            emit_struct_field(out, prefix, &field.name, &field.ty, field.codec.as_ref());
        }
        writeln!(out, "}} {prefix}_{snake}_t;\n").unwrap();
    }
}

fn emit_decode_fns(out: &mut String, prefix: &str, types: &[IdlTypeDef]) {
    for td in types {
        if td.fields.is_empty() {
            continue;
        }
        let snake = pascal_to_snake(&td.name);
        writeln!(
            out,
            "static inline bool {prefix}_{snake}_decode(\n    const uint8_t *data,\n    uint64_t \
             data_len,\n    {prefix}_{snake}_t *out\n) {{",
        )
        .unwrap();
        writeln!(
            out,
            "    {prefix}_decoder_t decoder = {{ .data = data, .len = data_len, .offset = 0 }};"
        )
        .unwrap();
        let fixed_fields: Vec<_> = td
            .fields
            .iter()
            .filter(|field| !is_dynamic_field(field))
            .collect();
        let dynamic_fields: Vec<_> = td
            .fields
            .iter()
            .filter(|field| is_dynamic_field(field))
            .collect();
        for field in fixed_fields {
            out.push_str(&decode_field_expr(
                prefix,
                &field.name,
                &field.ty,
                field.codec.as_ref(),
                1,
                types,
            ));
        }
        for field in &dynamic_fields {
            out.push_str(&decode_dynamic_header(
                prefix,
                &field.name,
                &field.ty,
                field.codec.as_ref(),
                1,
            ));
        }
        for field in dynamic_fields {
            out.push_str(&decode_dynamic_tail(
                prefix,
                &field.name,
                &field.ty,
                field.codec.as_ref(),
                1,
                types,
            ));
        }
        out.push_str("    return decoder.offset == decoder.len;\n}\n\n");
    }
}

fn emit_instructions(out: &mut String, prefix: &str, idl: &Idl) {
    let upper = prefix.to_ascii_uppercase();

    for ix in &idl.instructions {
        let ix_snake = pascal_to_snake(&ix.name);
        let user_accounts: Vec<_> = ix
            .accounts
            .iter()
            .filter(|a| {
                a.optional
                    || !matches!(
                        a.resolver,
                        IdlResolver::Const { .. } | IdlResolver::Pda { .. }
                    )
            })
            .collect();
        let account_field_seeds = account_field_seed_inputs(ix);

        writeln!(out, "typedef struct {{").unwrap();
        for acc in &user_accounts {
            writeln!(out, "    Pubkey *{};", acc.name).unwrap();
        }
        for (path, field) in &account_field_seeds {
            let name = account_field_seed_input_name(path, field);
            writeln!(out, "    const uint8_t *{name};").unwrap();
            writeln!(out, "    uint64_t {name}_len;").unwrap();
        }
        if user_accounts.is_empty() && account_field_seeds.is_empty() {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        writeln!(out, "}} {prefix}_{ix_snake}_accounts_t;\n").unwrap();

        let has_args = !ix.args.is_empty();
        writeln!(out, "typedef struct {{").unwrap();
        if !has_args {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        for arg in &ix.args {
            emit_struct_field(out, prefix, &arg.name, &arg.ty, arg.codec.as_ref());
        }
        writeln!(out, "}} {prefix}_{ix_snake}_args_t;\n").unwrap();

        let disc_len = ix.discriminator.len();
        let num_accounts = ix.accounts.len();
        let uses_compact_layout = ix
            .args
            .iter()
            .any(|arg| is_dynamic_with_codec(&arg.ty, arg.codec.as_ref()));
        let pda_count = ix
            .accounts
            .iter()
            .filter(|a| !a.optional && matches!(a.resolver, IdlResolver::Pda { .. }))
            .count();
        let pda_key_params = if pda_count > 0 {
            "    Pubkey *pda_key_buf,\n    uint64_t pda_key_buf_capacity,\n    "
        } else {
            "    "
        };
        if ix.remaining_accounts.is_some() {
            writeln!(
                out,
                "static inline {prefix}_ix_result_t {prefix}_{ix_snake}_ix(\n    \
                 {prefix}_{ix_snake}_accounts_t *accounts,\n    {prefix}_{ix_snake}_args_t \
                 *args,\n    const AccountMeta *remaining,\n    uint64_t remaining_len,\n    \
                 Instruction *ix_out,\n    AccountMeta *meta_buf,\n    uint64_t \
                 meta_buf_capacity,\n{pda_key_params}uint8_t *data_buf,\n    uint64_t \
                 data_buf_capacity\n) {{",
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "static inline {prefix}_ix_result_t {prefix}_{ix_snake}_ix(\n    \
                 {prefix}_{ix_snake}_accounts_t *accounts,\n    {prefix}_{ix_snake}_args_t \
                 *args,\n    Instruction *ix_out,\n    AccountMeta *meta_buf,\n    uint64_t \
                 meta_buf_capacity,\n{pda_key_params}uint8_t *data_buf,\n    uint64_t \
                 data_buf_capacity\n) {{",
            )
            .unwrap();
        }

        if user_accounts.is_empty() && account_field_seeds.is_empty() {
            writeln!(out, "    (void)accounts;").unwrap();
        }
        if !has_args {
            writeln!(out, "    (void)args;").unwrap();
        }
        writeln!(out, "    const uint64_t required_pda_keys = {pda_count};").unwrap();

        if ix.remaining_accounts.is_some() {
            writeln!(
                out,
                "    if (remaining_len > ((uint64_t)-1) - {num_accounts}) return \
                 ({prefix}_ix_result_t){{ .status = {upper}_IX_LENGTH_OVERFLOW, .accounts_len = \
                 (uint64_t)-1, .data_len = 0, .pda_keys_len = required_pda_keys, .pda_status = \
                 SUCCESS }};"
            )
            .unwrap();
            writeln!(
                out,
                "    uint64_t required_accounts = {num_accounts} + remaining_len;"
            )
            .unwrap();
        } else {
            writeln!(out, "    uint64_t required_accounts = {num_accounts};").unwrap();
        }
        writeln!(out, "    uint64_t required_data = {disc_len};").unwrap();
        for arg in &ix.args {
            emit_required_data_size(
                out,
                prefix,
                &upper,
                &format!("args->{}", arg.name),
                &arg.ty,
                arg.codec.as_ref(),
                &idl.types,
                1,
                uses_compact_layout && is_dynamic_with_codec(&arg.ty, arg.codec.as_ref()),
            );
        }
        writeln!(
            out,
            "    if (meta_buf_capacity < required_accounts) return ({prefix}_ix_result_t){{ \
             .status = {upper}_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, \
             .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS \
             }};"
        )
        .unwrap();
        if pda_count > 0 {
            writeln!(
                out,
                "    if (pda_key_buf_capacity < required_pda_keys) return \
                 ({prefix}_ix_result_t){{ .status = {upper}_IX_PDA_KEY_BUFFER_TOO_SMALL, \
                 .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = \
                 required_pda_keys, .pda_status = SUCCESS }};"
            )
            .unwrap();
        }
        writeln!(
            out,
            "    if (data_buf_capacity < required_data) return ({prefix}_ix_result_t){{ .status = \
             {upper}_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = \
             required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS }};"
        )
        .unwrap();

        if pda_count > 0 {
            writeln!(out, "    Pubkey derived_pda_keys[{pda_count}];").unwrap();
        }

        let mut pda_name_to_idx: HashMap<&str, usize> = HashMap::new();
        {
            let mut idx = 0usize;
            for acc in &ix.accounts {
                if !acc.optional && matches!(acc.resolver, IdlResolver::Pda { .. }) {
                    pda_name_to_idx.insert(acc.name.as_str(), idx);
                    idx += 1;
                }
            }
        }

        // derive pdas
        let mut pda_idx = 0usize;
        for acc in &ix.accounts {
            if !acc.optional {
                if let IdlResolver::Pda { ref seeds, .. } = acc.resolver {
                    emit_pda_derivation(out, prefix, seeds, &upper, pda_idx, &pda_name_to_idx);
                    pda_idx += 1;
                }
            }
        }
        if pda_count > 0 {
            writeln!(
                out,
                "    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = \
                 derived_pda_keys[i];"
            )
            .unwrap();
        }

        // build account metas
        pda_idx = 0;
        for (i, acc) in ix.accounts.iter().enumerate() {
            let key_expr = if acc.optional {
                // Optional accounts are nullable pointers; a NULL pointer is
                // encoded as the program id sentinel. This takes precedence
                // over any resolver so absence is always representable.
                format!(
                    "accounts->{n} ? accounts->{n} : (Pubkey *)&{upper}_PROGRAM_ID",
                    n = acc.name
                )
            } else if matches!(acc.resolver, IdlResolver::Pda { .. }) {
                let expr = format!("&pda_key_buf[{pda_idx}]");
                pda_idx += 1;
                expr
            } else if matches!(acc.resolver, IdlResolver::Const { .. }) {
                format!(
                    "(Pubkey *)&{}",
                    fixed_account_id_name(prefix, &ix.name, &acc.name)
                )
            } else {
                format!("accounts->{}", acc.name)
            };

            let helper = meta_helper(acc.writable.is_true(), acc.signer.is_true());
            writeln!(out, "    meta_buf[{i}] = {helper}({key_expr});").unwrap();
        }

        // serialize data
        writeln!(out, "    uint64_t off = 0;").unwrap();
        writeln!(
            out,
            "    for (uint64_t i = 0; i < {disc_len}; i++) data_buf[off++] = \
             {upper}_{ix_upper}_DISC[i];",
            ix_upper = ix_snake.to_ascii_uppercase(),
        )
        .unwrap();
        if has_args {
            if uses_compact_layout {
                for arg in ix
                    .args
                    .iter()
                    .filter(|arg| !is_dynamic_with_codec(&arg.ty, arg.codec.as_ref()))
                {
                    out.push_str(&serialize_field_expr(
                        &format!("args->{}", arg.name),
                        &arg.ty,
                        arg.codec.as_ref(),
                        &idl.types,
                        1,
                    ));
                }
                for arg in ix
                    .args
                    .iter()
                    .filter(|arg| is_dynamic_with_codec(&arg.ty, arg.codec.as_ref()))
                {
                    out.push_str(&serialize_compact_header_expr(
                        &format!("args->{}", arg.name),
                        &arg.ty,
                        arg.codec.as_ref(),
                        1,
                    ));
                }
                for arg in ix
                    .args
                    .iter()
                    .filter(|arg| is_dynamic_with_codec(&arg.ty, arg.codec.as_ref()))
                {
                    out.push_str(&serialize_compact_tail_expr(
                        &format!("args->{}", arg.name),
                        &arg.ty,
                        arg.codec.as_ref(),
                        1,
                    ));
                }
            } else {
                for arg in &ix.args {
                    out.push_str(&serialize_field_expr(
                        &format!("args->{}", arg.name),
                        &arg.ty,
                        arg.codec.as_ref(),
                        &idl.types,
                        1,
                    ));
                }
            }
        }

        // append remaining accounts
        if ix.remaining_accounts.is_some() {
            writeln!(
                out,
                "    for (uint64_t i = 0; i < remaining_len; i++) meta_buf[{num_accounts} + i] = \
                 remaining[i];"
            )
            .unwrap();
        }

        // assemble instruction
        writeln!(
            out,
            "    ix_out->program_id = (Pubkey *)&{upper}_PROGRAM_ID;"
        )
        .unwrap();
        writeln!(out, "    ix_out->accounts = meta_buf;").unwrap();
        writeln!(out, "    ix_out->accounts_len = required_accounts;").unwrap();
        writeln!(out, "    ix_out->data = data_buf;").unwrap();
        writeln!(out, "    ix_out->data_len = off;").unwrap();
        writeln!(
            out,
            "    return ({prefix}_ix_result_t){{ .status = {upper}_IX_OK, .accounts_len = \
             required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = \
             SUCCESS }};"
        )
        .unwrap();
        out.push_str("}\n\n");
    }
}

fn meta_helper(writable: bool, signer: bool) -> &'static str {
    match (writable, signer) {
        (true, true) => "meta_writable_signer",
        (true, false) => "meta_writable",
        (false, true) => "meta_readonly_signer",
        (false, false) => "meta_readonly",
    }
}

fn emit_pda_derivation(
    out: &mut String,
    prefix: &str,
    seeds: &[IdlPdaSeed],
    upper_prefix: &str,
    pda_idx: usize,
    pda_name_to_idx: &HashMap<&str, usize>,
) {
    let seed_count = seeds.len();
    writeln!(out, "    {{").unwrap();
    writeln!(out, "        SignerSeed seeds[{seed_count}];").unwrap();
    for (i, seed) in seeds.iter().enumerate() {
        match seed {
            IdlPdaSeed::Const { value } => {
                let hex = super::format_disc_hex(value);
                let len = value.len();
                writeln!(
                    out,
                    "        {{ static const uint8_t s[] = {{{hex}}}; seeds[{i}].addr = s; \
                     seeds[{i}].len = {len}; }}"
                )
                .unwrap();
            }
            IdlPdaSeed::Account { path } => {
                if let Some(&ref_idx) = pda_name_to_idx.get(path.as_str()) {
                    writeln!(
                        out,
                        "        seeds[{i}].addr = derived_pda_keys[{ref_idx}].bytes; \
                         seeds[{i}].len = 32;"
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "        seeds[{i}].addr = accounts->{path}->bytes; seeds[{i}].len = 32;"
                    )
                    .unwrap();
                }
            }
            IdlPdaSeed::AccountField { path, field, .. } => {
                let name = account_field_seed_input_name(path, field);
                writeln!(
                    out,
                    "        seeds[{i}].addr = accounts->{name}; seeds[{i}].len = \
                     accounts->{name}_len;"
                )
                .unwrap();
            }
            IdlPdaSeed::Arg { path, ty, .. } => emit_arg_seed(out, i, path, ty),
        }
    }
    writeln!(out, "        uint8_t bump;").unwrap();
    writeln!(
        out,
        "        uint64_t pda_status = find_program_address(seeds, {seed_count}, \
         &{upper_prefix}_PROGRAM_ID, &derived_pda_keys[{pda_idx}], &bump);"
    )
    .unwrap();
    writeln!(
        out,
        "        if (pda_status != SUCCESS) return ({prefix}_ix_result_t){{ .status = \
         {upper_prefix}_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = \
         required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status }};"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
}

fn emit_arg_seed(out: &mut String, index: usize, path: &str, ty: &IdlType) {
    let seed = format!("arg_seed_{index}");
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "pubkey" => {
                writeln!(
                    out,
                    "        seeds[{index}].addr = args->{path}.bytes; seeds[{index}].len = 32;"
                )
                .unwrap();
            }
            "bool" => {
                writeln!(out, "        uint8_t {seed}[1];").unwrap();
                writeln!(out, "        {seed}[0] = args->{path} ? 1 : 0;").unwrap();
                writeln!(
                    out,
                    "        seeds[{index}].addr = {seed}; seeds[{index}].len = 1;"
                )
                .unwrap();
            }
            "u8" | "i8" => {
                writeln!(out, "        uint8_t {seed}[1];").unwrap();
                writeln!(out, "        {seed}[0] = (uint8_t)args->{path};").unwrap();
                writeln!(
                    out,
                    "        seeds[{index}].addr = {seed}; seeds[{index}].len = 1;"
                )
                .unwrap();
            }
            "u16" | "i16" => emit_integer_arg_seed(out, index, path, 2, "uint16_t"),
            "u32" | "i32" => emit_integer_arg_seed(out, index, path, 4, "uint32_t"),
            "u64" | "i64" => emit_integer_arg_seed(out, index, path, 8, "uint64_t"),
            "u128" | "i128" => {
                writeln!(
                    out,
                    "        seeds[{index}].addr = args->{path}; seeds[{index}].len = 16;"
                )
                .unwrap();
            }
            _ => emit_raw_arg_seed(out, index, path),
        },
        IdlType::Array {
            array: (_inner, size),
        } => {
            writeln!(
                out,
                "        seeds[{index}].addr = args->{path}; seeds[{index}].len = {size};"
            )
            .unwrap();
        }
        _ => emit_raw_arg_seed(out, index, path),
    }
}

fn emit_integer_arg_seed(out: &mut String, index: usize, path: &str, width: usize, cast_ty: &str) {
    let seed = format!("arg_seed_{index}");
    writeln!(out, "        uint8_t {seed}[{width}];").unwrap();
    writeln!(
        out,
        "        {cast_ty} {seed}_value = ({cast_ty})args->{path};"
    )
    .unwrap();
    writeln!(
        out,
        "        for (int j = 0; j < {width}; j++) {seed}[j] = (uint8_t)({seed}_value >> (j * 8));"
    )
    .unwrap();
    writeln!(
        out,
        "        seeds[{index}].addr = {seed}; seeds[{index}].len = {width};"
    )
    .unwrap();
}

fn emit_raw_arg_seed(out: &mut String, index: usize, path: &str) {
    writeln!(
        out,
        "        seeds[{index}].addr = (const uint8_t *)args->{path}; seeds[{index}].len = \
         sizeof(args->{path});"
    )
    .unwrap();
}

fn account_field_seed_inputs(ix: &crate::types::IdlInstruction) -> Vec<(String, String)> {
    let mut inputs = Vec::new();
    for acc in &ix.accounts {
        if acc.optional {
            continue;
        }
        let IdlResolver::Pda { seeds, .. } = &acc.resolver else {
            continue;
        };
        for seed in seeds {
            let IdlPdaSeed::AccountField { path, field, .. } = seed else {
                continue;
            };
            if !inputs
                .iter()
                .any(|(seen_path, seen_field)| seen_path == path && seen_field == field)
            {
                inputs.push((path.clone(), field.clone()));
            }
        }
    }
    inputs
}

fn account_field_seed_input_name(path: &str, field: &str) -> String {
    format!(
        "{}_{}_seed",
        path,
        field.split('.').collect::<Vec<_>>().join("_")
    )
}

fn emit_error_codes(out: &mut String, prefix: &str, errors: &[crate::types::IdlErrorDef]) {
    if errors.is_empty() {
        return;
    }
    let upper = prefix.to_ascii_uppercase();
    for err in errors {
        let name = err.name.to_ascii_uppercase();
        writeln!(out, "#define {upper}_ERR_{name} {code}", code = err.code).unwrap();
    }
    out.push('\n');
}

fn primitive_c_type(primitive: &str) -> Option<&'static str> {
    match primitive {
        "bool" => Some("bool"),
        "u8" => Some("uint8_t"),
        "i8" => Some("int8_t"),
        "u16" => Some("uint16_t"),
        "i16" => Some("int16_t"),
        "u32" => Some("uint32_t"),
        "i32" => Some("int32_t"),
        "u64" => Some("uint64_t"),
        "i64" => Some("int64_t"),
        "u128" | "i128" => Some("uint8_t"),
        "f32" => Some("float"),
        "f64" => Some("double"),
        "pubkey" => Some("Pubkey"),
        "string" => Some("uint8_t *"),
        _ => None,
    }
}

fn builtin_defined_primitive(name: &str) -> Option<&'static str> {
    match name {
        "PodBool" => Some("bool"),
        "PodU8" => Some("u8"),
        "PodI8" => Some("i8"),
        "PodU16" => Some("u16"),
        "PodI16" => Some("i16"),
        "PodU32" => Some("u32"),
        "PodI32" => Some("i32"),
        "PodU64" => Some("u64"),
        "PodI64" => Some("i64"),
        "PodU128" => Some("u128"),
        "PodI128" => Some("i128"),
        _ => None,
    }
}

fn c_type(ty: &IdlType, prefix: &str) -> String {
    match ty {
        IdlType::Primitive(p) => primitive_c_type(p).unwrap_or("uint8_t *").into(),
        IdlType::Option { option } => c_type(option, prefix),
        IdlType::Vec { .. } => "uint8_t *".into(),
        IdlType::Array {
            array: (_inner, size),
        } => format!("uint8_t[{size}]"),
        IdlType::Defined { defined } => {
            if let Some(primitive) = builtin_defined_primitive(&defined.name) {
                return primitive_c_type(primitive).unwrap_or("uint8_t *").into();
            }
            format!("{prefix}_{}_t", pascal_to_snake(&defined.name))
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}

fn is_fixed_array_type(ty: &IdlType) -> bool {
    matches!(ty, IdlType::Array { .. })
}

fn fixed_array_size(ty: &IdlType) -> usize {
    match ty {
        IdlType::Array {
            array: (_inner, size),
        } => *size,
        _ => 1,
    }
}

fn is_128bit(ty: &IdlType) -> bool {
    matches!(ty, IdlType::Primitive(p) if p == "u128" || p == "i128")
}

fn is_dynamic_with_codec(ty: &IdlType, codec: Option<&IdlCodec>) -> bool {
    codec.is_some() && dynamic_payload_type(ty).is_some()
}

fn is_dynamic_field(field: &crate::types::IdlFieldDef) -> bool {
    is_dynamic_with_codec(&field.ty, field.codec.as_ref())
}

fn dynamic_payload_type(ty: &IdlType) -> Option<&IdlType> {
    match ty {
        IdlType::Primitive(p) if p == "string" => Some(ty),
        IdlType::Vec { .. } => Some(ty),
        IdlType::Option { option } => dynamic_payload_type(option),
        _ => None,
    }
}

fn emit_struct_field(
    out: &mut String,
    prefix: &str,
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
) {
    let (is_opt, inner, inner_codec) = match ty {
        IdlType::Option { option } => (true, option.as_ref(), codec),
        other => (false, other, codec),
    };
    if is_opt {
        writeln!(out, "    bool {name}_present;").unwrap();
    }
    if let IdlType::Defined { defined } = inner {
        if let Some(primitive) = builtin_defined_primitive(&defined.name) {
            if primitive == "u128" || primitive == "i128" {
                writeln!(out, "    uint8_t {name}[16];").unwrap();
            } else {
                writeln!(
                    out,
                    "    {} {name};",
                    primitive_c_type(primitive).unwrap_or("uint8_t *")
                )
                .unwrap();
            }
            return;
        }
    }
    if is_dynamic_with_codec(inner, inner_codec) {
        match inner {
            IdlType::Vec { vec } if matches!(&**vec, IdlType::Primitive(p) if p == "pubkey") => {
                writeln!(out, "    const Pubkey *{name};").unwrap();
            }
            _ => {
                writeln!(out, "    const uint8_t *{name};").unwrap();
            }
        }
        writeln!(out, "    uint32_t {name}_len;").unwrap();
    } else if is_fixed_array_type(inner) {
        let size = fixed_array_size(inner);
        writeln!(out, "    uint8_t {name}[{size}];").unwrap();
    } else if is_128bit(inner) {
        writeln!(out, "    uint8_t {name}[16];").unwrap();
    } else {
        writeln!(out, "    {} {name};", c_type(inner, prefix)).unwrap();
    }
}

#[allow(clippy::too_many_arguments)]
fn emit_required_data_size(
    out: &mut String,
    prefix: &str,
    upper: &str,
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    types: &[IdlTypeDef],
    indent: usize,
    compact_dynamic: bool,
) {
    let t = "    ".repeat(indent);
    if compact_dynamic {
        let payload = dynamic_payload_type(ty).expect("compact dynamic payload");
        let (item_size, _, _) = dynamic_c_info(payload);
        if matches!(ty, IdlType::Option { .. }) {
            emit_size_add(out, prefix, upper, "1", &t);
            writeln!(out, "{t}if ({name}_present) {{").unwrap();
            let ti = "    ".repeat(indent + 1);
            emit_size_add(
                out,
                prefix,
                upper,
                &codec
                    .expect("compact dynamic codec")
                    .prefix_bytes()
                    .to_string(),
                &ti,
            );
            emit_size_add_items(out, prefix, upper, &format!("{name}_len"), item_size, &ti);
            writeln!(out, "{t}}}").unwrap();
        } else {
            emit_size_add(
                out,
                prefix,
                upper,
                &codec
                    .expect("compact dynamic codec")
                    .prefix_bytes()
                    .to_string(),
                &t,
            );
            emit_size_add_items(out, prefix, upper, &format!("{name}_len"), item_size, &t);
        }
        return;
    }

    match ty {
        IdlType::Primitive(primitive) => match primitive.as_str() {
            "bool" | "u8" | "i8" => emit_size_add(out, prefix, upper, "1", &t),
            "u16" | "i16" => emit_size_add(out, prefix, upper, "2", &t),
            "u32" | "i32" | "f32" => emit_size_add(out, prefix, upper, "4", &t),
            "u64" | "i64" | "f64" => emit_size_add(out, prefix, upper, "8", &t),
            "u128" | "i128" => emit_size_add(out, prefix, upper, "16", &t),
            "pubkey" => emit_size_add(out, prefix, upper, "32", &t),
            "string" => {
                emit_size_add(
                    out,
                    prefix,
                    upper,
                    &codec.map(IdlCodec::prefix_bytes).unwrap_or(4).to_string(),
                    &t,
                );
                emit_size_add_items(out, prefix, upper, &format!("{name}_len"), 1, &t);
            }
            _ => {}
        },
        IdlType::Option { option } => {
            emit_size_add(out, prefix, upper, "1", &t);
            writeln!(out, "{t}if ({name}_present) {{").unwrap();
            emit_required_data_size(
                out,
                prefix,
                upper,
                name,
                option,
                None,
                types,
                indent + 1,
                false,
            );
            writeln!(out, "{t}}}").unwrap();
        }
        IdlType::Defined { defined } => {
            if let Some(primitive) = builtin_defined_primitive(&defined.name) {
                emit_required_data_size(
                    out,
                    prefix,
                    upper,
                    name,
                    &IdlType::Primitive(primitive.into()),
                    None,
                    types,
                    indent,
                    false,
                );
            } else if let Some(td) = types
                .iter()
                .find(|candidate| candidate.name == defined.name)
            {
                for field in &td.fields {
                    emit_required_data_size(
                        out,
                        prefix,
                        upper,
                        &format!("{name}.{}", field.name),
                        &field.ty,
                        field.codec.as_ref(),
                        types,
                        indent,
                        false,
                    );
                }
            }
        }
        IdlType::Vec { .. } => {
            emit_size_add(
                out,
                prefix,
                upper,
                &codec.map(IdlCodec::prefix_bytes).unwrap_or(4).to_string(),
                &t,
            );
            emit_size_add_items(out, prefix, upper, &format!("{name}_len"), 1, &t);
        }
        IdlType::Array {
            array: (_inner, size),
        } => emit_size_add(out, prefix, upper, &size.to_string(), &t),
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}

fn emit_size_add(out: &mut String, prefix: &str, upper: &str, amount: &str, t: &str) {
    writeln!(
        out,
        "{t}if (!{prefix}_ix_size_add(&required_data, {amount})) return ({prefix}_ix_result_t){{ \
         .status = {upper}_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = \
         (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS }};"
    )
    .unwrap();
}

fn emit_size_add_items(
    out: &mut String,
    prefix: &str,
    upper: &str,
    count: &str,
    item_size: usize,
    t: &str,
) {
    writeln!(
        out,
        "{t}if (!{prefix}_ix_size_add_items(&required_data, {count}, {item_size})) return \
         ({prefix}_ix_result_t){{ .status = {upper}_IX_LENGTH_OVERFLOW, .accounts_len = \
         required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, \
         .pda_status = SUCCESS }};"
    )
    .unwrap();
}

fn serialize_dyn_bytes(name: &str, prefix_bytes: usize, t: &str) -> String {
    let write_prefix = match prefix_bytes {
        1 => format!("{t}data_buf[off++] = (uint8_t){name}_len;\n"),
        2 => format!(
            "{t}{{ uint16_t slen = (uint16_t){name}_len; data_buf[off] = (uint8_t)slen; \
             data_buf[off+1] = (uint8_t)(slen >> 8); off += 2; }}\n"
        ),
        4 => format!(
            "{t}{{ uint32_t slen = {name}_len; data_buf[off] = (uint8_t)slen; data_buf[off+1] = \
             (uint8_t)(slen >> 8); data_buf[off+2] = (uint8_t)(slen >> 16); data_buf[off+3] = \
             (uint8_t)(slen >> 24); off += 4; }}\n"
        ),
        _ => format!(
            "{t}{{ uint64_t slen = (uint64_t){name}_len; for (int i = 0; i < 8; i++) {{ \
             data_buf[off + i] = (uint8_t)(slen >> (i * 8)); }} off += 8; }}\n"
        ),
    };
    format!(
        "{write_prefix}{t}for (uint32_t i = 0; i < {name}_len; i++) data_buf[off++] = {name}[i];\n"
    )
}

fn serialize_prefix_expr(len_expr: &str, prefix_bytes: usize, t: &str) -> String {
    match prefix_bytes {
        1 => format!("{t}data_buf[off++] = (uint8_t){len_expr};\n"),
        2 => format!(
            "{t}{{ uint16_t slen = (uint16_t){len_expr}; data_buf[off] = (uint8_t)slen; \
             data_buf[off+1] = (uint8_t)(slen >> 8); off += 2; }}\n"
        ),
        4 => format!(
            "{t}{{ uint32_t slen = {len_expr}; data_buf[off] = (uint8_t)slen; data_buf[off+1] = \
             (uint8_t)(slen >> 8); data_buf[off+2] = (uint8_t)(slen >> 16); data_buf[off+3] = \
             (uint8_t)(slen >> 24); off += 4; }}\n"
        ),
        _ => format!(
            "{t}{{ uint64_t slen = (uint64_t){len_expr}; for (int i = 0; i < 8; i++) {{ \
             data_buf[off + i] = (uint8_t)(slen >> (i * 8)); }} off += 8; }}\n"
        ),
    }
}

fn serialize_compact_header_expr(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    indent: usize,
) -> String {
    let t = "    ".repeat(indent);
    if matches!(ty, IdlType::Option { .. }) {
        return format!("{t}data_buf[off++] = {name}_present ? 1 : 0;\n");
    }
    serialize_prefix_expr(
        &format!("{name}_len"),
        codec.map(IdlCodec::prefix_bytes).unwrap_or(4),
        &t,
    )
}

fn serialize_compact_tail_expr(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    indent: usize,
) -> String {
    let t = "    ".repeat(indent);
    let Some(payload_ty) = dynamic_payload_type(ty) else {
        return String::new();
    };
    let prefix_bytes = codec.map(IdlCodec::prefix_bytes).unwrap_or(4);
    let mut out = String::new();
    if matches!(ty, IdlType::Option { .. }) {
        writeln!(out, "{t}if ({name}_present) {{").unwrap();
        let ti = "    ".repeat(indent + 1);
        out.push_str(&serialize_prefix_expr(
            &format!("{name}_len"),
            prefix_bytes,
            &ti,
        ));
        out.push_str(&serialize_payload_bytes(name, payload_ty, &ti));
        writeln!(out, "{t}}}").unwrap();
    } else {
        out.push_str(&serialize_payload_bytes(name, payload_ty, &t));
    }
    out
}

fn serialize_payload_bytes(name: &str, ty: &IdlType, t: &str) -> String {
    match ty {
        IdlType::Vec { vec } if matches!(&**vec, IdlType::Primitive(p) if p == "pubkey") => {
            format!(
                "{t}for (uint32_t i = 0; i < {name}_len; i++) {{ for (int j = 0; j < 32; j++) \
                 data_buf[off++] = {name}[i].bytes[j]; }}\n"
            )
        }
        _ => format!("{t}for (uint32_t i = 0; i < {name}_len; i++) data_buf[off++] = {name}[i];\n"),
    }
}

fn decode_dyn_bytes(
    prefix: &str,
    name: &str,
    prefix_bytes: usize,
    item_size: usize,
    pointer_cast: &str,
    utf8: bool,
    t: &str,
) -> String {
    let utf8_check = if utf8 {
        format!("{t}if (!{prefix}_utf8_valid({name}_bytes, out->{name}_len)) return false;\n")
    } else {
        String::new()
    };
    format!(
        "{t}const uint8_t *{name}_bytes;\n{t}if (!{prefix}_decoder_span(&decoder, {prefix_bytes}, \
         {item_size}, &{name}_bytes, &out->{name}_len)) return false;\n{utf8_check}{t}out->{name} \
         = {pointer_cast}{name}_bytes;\n"
    )
}

fn serialize_field_expr(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    types: &[IdlTypeDef],
    indent: usize,
) -> String {
    let t = "    ".repeat(indent);

    // Handle dynamic string with codec
    if let IdlType::Primitive(p) = ty {
        if p == "string" {
            if let Some(c) = codec {
                return serialize_dyn_bytes(name, c.prefix_bytes(), &t);
            }
        }
    }

    // Handle Vec with codec
    if let IdlType::Vec { .. } = ty {
        if let Some(c) = codec {
            return serialize_dyn_bytes(name, c.prefix_bytes(), &t);
        }
    }

    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!("{t}data_buf[off++] = {name} ? 1 : 0;\n"),
            "u8" => format!("{t}data_buf[off++] = {name};\n"),
            "i8" => format!("{t}data_buf[off++] = (uint8_t){name};\n"),
            "u16" => format!(
                "{t}{{ uint16_t v = {name}; data_buf[off] = (uint8_t)v; data_buf[off+1] = \
                 (uint8_t)(v >> 8); off += 2; }}\n"
            ),
            "i16" => format!(
                "{t}{{ uint16_t v = (uint16_t){name}; data_buf[off] = (uint8_t)v; data_buf[off+1] \
                 = (uint8_t)(v >> 8); off += 2; }}\n"
            ),
            "u32" | "f32" => {
                let cast = if p == "f32" {
                    "uint32_t v; {{ union {{ float f; uint32_t u; }} c; c.f = NAME; v = c.u; }}"
                        .replace("NAME", name)
                } else {
                    format!("uint32_t v = {name};")
                };
                format!(
                    "{t}{{ {cast} data_buf[off] = (uint8_t)v; data_buf[off+1] = (uint8_t)(v >> \
                     8); data_buf[off+2] = (uint8_t)(v >> 16); data_buf[off+3] = (uint8_t)(v >> \
                     24); off += 4; }}\n"
                )
            }
            "u64" | "i64" | "f64" => {
                let cast = if p == "f64" {
                    "uint64_t v; {{ union {{ double f; uint64_t u; }} c; c.f = NAME; v = c.u; }}"
                        .replace("NAME", name)
                } else if p == "i64" {
                    format!("uint64_t v = (uint64_t){name};")
                } else {
                    format!("uint64_t v = {name};")
                };
                format!(
                    "{t}{{ {cast} for (int i = 0; i < 8; i++) {{ data_buf[off + i] = (uint8_t)(v \
                     >> (i * 8)); }} off += 8; }}\n"
                )
            }
            "u128" | "i128" => format!(
                "{t}for (int i = 0; i < 16; i++) data_buf[off + i] = {name}[i]; off += 16;\n"
            ),
            "pubkey" => format!(
                "{t}for (int i = 0; i < 32; i++) data_buf[off + i] = {name}.bytes[i]; off += 32;\n"
            ),
            "string" => {
                // Plain string without codec uses a Borsh-style u32 prefix.
                serialize_dyn_bytes(name, 4, &t)
            }
            _ => format!("{t}/* unsupported type for {name} */\n"),
        },
        IdlType::Option { option } => {
            let ti = "    ".repeat(indent + 1);
            let inner = serialize_field_expr(name, option, None, types, indent + 1);
            format!(
                "{t}if ({name}_present) {{\n{ti}data_buf[off++] = 1;\n{inner}{t}}} else \
                 {{\n{ti}data_buf[off++] = 0;\n{t}}}\n"
            )
        }
        IdlType::Defined { defined } => {
            if let Some(primitive) = builtin_defined_primitive(&defined.name) {
                return serialize_field_expr(
                    name,
                    &IdlType::Primitive(primitive.into()),
                    None,
                    types,
                    indent,
                );
            }
            if let Some(td) = types.iter().find(|t| t.name == defined.name) {
                let mut result = String::new();
                for field in &td.fields {
                    result.push_str(&serialize_field_expr(
                        &format!("{name}.{f}", f = field.name),
                        &field.ty,
                        field.codec.as_ref(),
                        types,
                        indent,
                    ));
                }
                result
            } else {
                format!("{t}/* unknown defined type: {} */\n", defined.name)
            }
        }
        IdlType::Vec { .. } => {
            // Vec without codec uses a Borsh-style u32 prefix.
            serialize_dyn_bytes(name, 4, &t)
        }
        IdlType::Array {
            array: (_inner, size),
        } => {
            format!(
                "{t}for (int i = 0; i < {size}; i++) data_buf[off + i] = {name}[i]; off += \
                 {size};\n"
            )
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}

fn dynamic_c_info(ty: &IdlType) -> (usize, &'static str, bool) {
    match ty {
        IdlType::Primitive(primitive) if primitive == "string" => (1, "", true),
        IdlType::Vec { vec } if matches!(&**vec, IdlType::Primitive(p) if p == "pubkey") => {
            (32, "(const Pubkey *)", false)
        }
        IdlType::Vec { .. } => (1, "", false),
        _ => (1, "", false),
    }
}

fn decode_dynamic_header(
    prefix: &str,
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
) -> String {
    let t = "    ".repeat(depth);
    if matches!(ty, IdlType::Option { .. }) {
        return format!(
            "{t}uint64_t {name}_tag; if (!{prefix}_decoder_uint(&decoder, 1, &{name}_tag) || \
             {name}_tag > 1) return false;\n"
        );
    }
    let width = codec.expect("dynamic field codec").prefix_bytes();
    format!(
        "{t}{{ uint64_t count; if (!{prefix}_decoder_uint(&decoder, {width}, &count) || count > \
         ((uint32_t)-1)) return false; out->{name}_len = (uint32_t)count; }}\n"
    )
}

fn decode_dynamic_tail(
    prefix: &str,
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
    _types: &[IdlTypeDef],
) -> String {
    let t = "    ".repeat(depth);
    if let IdlType::Option { option } = ty {
        let (item_size, pointer_cast, utf8) = dynamic_c_info(option);
        let inner = decode_dyn_bytes(
            prefix,
            name,
            codec.expect("dynamic field codec").prefix_bytes(),
            item_size,
            pointer_cast,
            utf8,
            &format!("{t}    "),
        );
        return format!(
            "{t}if ({name}_tag == 0) {{\n{t}    out->{name}_present = 0;\n{t}}} else {{\n{t}    \
             out->{name}_present = 1;\n{inner}{t}}}\n"
        );
    }
    let (item_size, pointer_cast, utf8) = dynamic_c_info(ty);
    let utf8_check = if utf8 {
        format!("{t}if (!{prefix}_utf8_valid({name}_bytes, out->{name}_len)) return false;\n")
    } else {
        String::new()
    };
    format!(
        "{t}const uint8_t *{name}_bytes;\n{t}if (!{prefix}_decoder_take(&decoder, \
         (uint64_t)out->{name}_len * {item_size}, &{name}_bytes)) return \
         false;\n{utf8_check}{t}out->{name} = {pointer_cast}{name}_bytes;\n"
    )
}

fn decode_field_expr(
    prefix: &str,
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
    types: &[IdlTypeDef],
) -> String {
    let t = "    ".repeat(depth);

    // Handle dynamic string with codec
    if let IdlType::Primitive(p) = ty {
        if p == "string" {
            if let Some(c) = codec {
                return decode_dyn_bytes(prefix, name, c.prefix_bytes(), 1, "", true, &t);
            }
        }
    }

    // Handle Vec with codec
    if let IdlType::Vec { vec } = ty {
        if let Some(c) = codec {
            let is_pubkey = matches!(&**vec, IdlType::Primitive(p) if p == "pubkey");
            return decode_dyn_bytes(
                prefix,
                name,
                c.prefix_bytes(),
                if is_pubkey { 32 } else { 1 },
                if is_pubkey { "(const Pubkey *)" } else { "" },
                false,
                &t,
            );
        }
    }

    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 1, &v) || v > 1) return \
                 false; out->{name} = v == 1; }}\n"
            ),
            "u8" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 1, &v)) return false; \
                 out->{name} = (uint8_t)v; }}\n"
            ),
            "i8" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 1, &v)) return false; \
                 out->{name} = (int8_t)v; }}\n"
            ),
            "u16" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 2, &v)) return false; \
                 out->{name} = (uint16_t)v; }}\n"
            ),
            "i16" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 2, &v)) return false; \
                 out->{name} = (int16_t)v; }}\n"
            ),
            "u32" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 4, &v)) return false; \
                 out->{name} = (uint32_t)v; }}\n"
            ),
            "i32" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 4, &v)) return false; \
                 out->{name} = (int32_t)v; }}\n"
            ),
            "u64" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 8, &v)) return false; \
                 out->{name} = v; }}\n"
            ),
            "i64" => format!(
                "{t}{{ uint64_t v; if (!{prefix}_decoder_uint(&decoder, 8, &v)) return false; \
                 out->{name} = (int64_t)v; }}\n"
            ),
            "f32" => format!(
                "{t}{{ uint64_t v; union {{ uint32_t u; float f; }} c; if \
                 (!{prefix}_decoder_uint(&decoder, 4, &v)) return false; c.u = (uint32_t)v; \
                 out->{name} = c.f; }}\n"
            ),
            "f64" => format!(
                "{t}{{ union {{ uint64_t u; double f; }} c; if (!{prefix}_decoder_uint(&decoder, \
                 8, &c.u)) return false; out->{name} = c.f; }}\n"
            ),
            "u128" | "i128" => format!(
                "{t}{{ const uint8_t *bytes; if (!{prefix}_decoder_take(&decoder, 16, &bytes)) \
                 return false; for (int i = 0; i < 16; i++) out->{name}[i] = bytes[i]; }}\n"
            ),
            "pubkey" => format!(
                "{t}{{ const uint8_t *bytes; if (!{prefix}_decoder_take(&decoder, 32, &bytes)) \
                 return false; for (int i = 0; i < 32; i++) out->{name}.bytes[i] = bytes[i]; }}\n"
            ),
            "string" => {
                // Plain string without codec uses a Borsh-style u32 prefix.
                decode_dyn_bytes(prefix, name, 4, 1, "", true, &t)
            }
            _ => format!("{t}/* unsupported decode for {name} */\n"),
        },
        IdlType::Vec { vec } => {
            // Vec without codec uses a Borsh-style u32 prefix.
            let is_pubkey = matches!(&**vec, IdlType::Primitive(p) if p == "pubkey");
            decode_dyn_bytes(
                prefix,
                name,
                4,
                if is_pubkey { 32 } else { 1 },
                if is_pubkey { "(const Pubkey *)" } else { "" },
                false,
                &t,
            )
        }
        IdlType::Array {
            array: (_inner, size),
        } => {
            format!(
                "{t}{{ const uint8_t *bytes; if (!{prefix}_decoder_take(&decoder, {size}, \
                 &bytes)) return false; for (uint64_t i = 0; i < {size}; i++) out->{name}[i] = \
                 bytes[i]; }}\n"
            )
        }
        IdlType::Option { option } => {
            let inner = decode_field_expr(prefix, name, option, codec, depth + 1, types);
            let ti = "    ".repeat(depth + 1);
            format!(
                "{t}{{ uint64_t tag; if (!{prefix}_decoder_uint(&decoder, 1, &tag) || tag > 1) \
                 return false;\n{ti}if (tag == 1) {{\n{ti}    out->{name}_present = \
                 1;\n{inner}{ti}}} else {{\n{ti}    out->{name}_present = 0;\n{ti}}}\n{t}}}\n"
            )
        }
        IdlType::Defined { defined } => {
            if let Some(primitive) = builtin_defined_primitive(&defined.name) {
                return decode_field_expr(
                    prefix,
                    name,
                    &IdlType::Primitive(primitive.into()),
                    None,
                    depth,
                    types,
                );
            }
            if let Some(td) = types.iter().find(|t| t.name == defined.name) {
                let mut result = String::new();
                for field in &td.fields {
                    result.push_str(&decode_field_expr(
                        prefix,
                        &format!("{name}.{f}", f = field.name),
                        &field.ty,
                        field.codec.as_ref(),
                        depth,
                        types,
                    ));
                }
                result
            } else {
                format!("{t}/* unknown defined type: {} */\n", defined.name)
            }
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}
