use {
    super::model::{go_field_path, reject_generics, CodegenResult, ProgramModel},
    crate::types::{
        Idl, IdlArg, IdlCodec, IdlFieldDef, IdlPdaSeed, IdlResolver, IdlType, IdlTypeDef,
    },
    quasar_schema::{snake_to_pascal, to_camel_case},
    std::fmt::Write,
};

/// Generate a Go client package from the IDL.
///
/// Uses `gagliardetto/solana-go` for Solana types (PublicKey, Instruction,
/// AccountMeta).
pub fn generate_go_client(idl: &Idl) -> CodegenResult<String> {
    let model = ProgramModel::try_new(idl)?;
    reject_generics(idl, "Go")?;
    let pkg_name = model.identity.go_package.clone();
    let mut out = String::new();

    // Package + imports
    writeln!(out, "// Code generated by quasar. DO NOT EDIT.").unwrap();
    writeln!(out, "package {}\n", pkg_name).unwrap();

    let has_events = model.features.has_events;
    let has_args = model.features.has_args;
    let has_types_with_fields = idl.types.iter().any(|t| !t.fields.is_empty());
    let needs_binary = has_args || has_events || has_types_with_fields;
    let has_floats = model.features.has_float;

    out.push_str("import (\n");
    if has_types_with_fields || has_events {
        out.push_str("\t\"errors\"\n");
    }
    if needs_binary {
        out.push_str("\t\"encoding/binary\"\n");
    }
    if has_events {
        out.push_str("\t\"bytes\"\n");
    }
    if has_floats {
        out.push_str("\t\"math\"\n");
    }
    if has_types_with_fields {
        out.push_str("\t\"unicode/utf8\"\n");
    }
    out.push('\n');
    out.push_str("\tsolana \"github.com/gagliardetto/solana-go\"\n");
    out.push_str(")\n\n");

    // Program ID
    writeln!(
        out,
        "var ProgramID = solana.MustPublicKeyFromBase58(\"{}\")\n",
        idl.address
    )
    .unwrap();

    if has_types_with_fields {
        out.push_str(
            "const maxDecodeElements = 10 * 1024 * 1024\n\ntype quasarDecoder struct {\n\tdata \
             []byte\n\toffset int\n\terr error\n}\n\nfunc (d *quasarDecoder) fail(message string) \
             {\n\tif d.err == nil { d.err = errors.New(message) }\n}\n\nfunc (d *quasarDecoder) \
             take(size int) []byte {\n\tif d.err != nil { return nil }\n\tif size < 0 || d.offset \
             < 0 || size > len(d.data)-d.offset {\n\t\td.fail(\"truncated input\")\n\t\treturn \
             nil\n\t}\n\tend := d.offset + size\n\tvalue := d.data[d.offset:end]\n\td.offset = \
             end\n\treturn value\n}\n\nfunc (d *quasarDecoder) length(width int) int {\n\traw := \
             d.take(width)\n\tif d.err != nil { return 0 }\n\tvar value uint64\n\tswitch width \
             {\n\tcase 1: value = uint64(raw[0])\n\tcase 2: value = \
             uint64(binary.LittleEndian.Uint16(raw))\n\tcase 4: value = \
             uint64(binary.LittleEndian.Uint32(raw))\n\tcase 8: value = \
             binary.LittleEndian.Uint64(raw)\n\tdefault: d.fail(\"invalid length prefix width\"); \
             return 0\n\t}\n\tif value > uint64(^uint(0)>>1) { d.fail(\"length overflows int\"); \
             return 0 }\n\treturn int(value)\n}\n\nfunc (d *quasarDecoder) u8() uint8 {\n\traw := \
             d.take(1); if d.err != nil { return 0 }; return raw[0]\n}\n\nfunc (d *quasarDecoder) \
             u16() uint16 {\n\traw := d.take(2); if d.err != nil { return 0 }; return \
             binary.LittleEndian.Uint16(raw)\n}\n\nfunc (d *quasarDecoder) u32() uint32 {\n\traw \
             := d.take(4); if d.err != nil { return 0 }; return \
             binary.LittleEndian.Uint32(raw)\n}\n\nfunc (d *quasarDecoder) u64() uint64 {\n\traw \
             := d.take(8); if d.err != nil { return 0 }; return \
             binary.LittleEndian.Uint64(raw)\n}\n\nfunc (d *quasarDecoder) elements(width int) \
             int {\n\tcount := d.length(width)\n\tif count > maxDecodeElements || count > \
             len(d.data)-d.offset { d.fail(\"element count exceeds limit\"); return 0 }\n\treturn \
             count\n}\n\nfunc (d *quasarDecoder) bool() bool {\n\traw := d.u8()\n\tif d.err != \
             nil { return false }\n\tif raw > 1 { d.fail(\"invalid bool\"); return false \
             }\n\treturn raw == 1\n}\n\nfunc (d *quasarDecoder) string(size int) string {\n\traw \
             := d.take(size)\n\tif d.err != nil { return \"\" }\n\tif !utf8.Valid(raw) { \
             d.fail(\"invalid UTF-8\"); return \"\" }\n\treturn string(raw)\n}\n\nfunc (d \
             *quasarDecoder) finish() error {\n\tif d.err != nil { return d.err }\n\tif d.offset \
             != len(d.data) { return errors.New(\"trailing bytes\") }\n\treturn nil\n}\n\n",
        );
    }

    // Discriminator variables
    for ix in &idl.instructions {
        let name = snake_to_pascal(&ix.name);
        writeln!(
            out,
            "var {}Discriminator = [{}]byte{{{}}}",
            name,
            ix.discriminator.len(),
            super::format_disc_hex(&ix.discriminator),
        )
        .unwrap();
    }
    if !idl.instructions.is_empty() {
        out.push('\n');
    }

    for acc in &idl.accounts {
        let name = snake_to_pascal(&acc.name);
        writeln!(
            out,
            "var {}AccountDiscriminator = [{}]byte{{{}}}",
            name,
            acc.discriminator.len(),
            super::format_disc_hex(&acc.discriminator),
        )
        .unwrap();
    }
    if !idl.accounts.is_empty() {
        out.push('\n');
    }

    for ev in &idl.events {
        let name = snake_to_pascal(&ev.name);
        writeln!(
            out,
            "var {}EventDiscriminator = [{}]byte{{{}}}",
            name,
            ev.discriminator.len(),
            super::format_disc_hex(&ev.discriminator),
        )
        .unwrap();
    }
    if !idl.events.is_empty() {
        out.push('\n');
    }

    // Type definitions (structs)
    for type_def in &idl.types {
        writeln!(out, "type {} struct {{", type_def.name).unwrap();
        for field in &type_def.fields {
            writeln!(
                out,
                "\t{} {}",
                snake_to_pascal(&field.name),
                go_type(&field.ty),
            )
            .unwrap();
        }
        out.push_str("}\n\n");

        // Decode function
        if !type_def.fields.is_empty() {
            writeln!(
                out,
                "func Decode{}(data []byte) (*{}, error) {{",
                type_def.name, type_def.name
            )
            .unwrap();
            out.push_str("\tdecoder := quasarDecoder{data: data}\n");
            let fixed_fields: Vec<_> = type_def
                .fields
                .iter()
                .filter(|field| !is_dynamic_field(field))
                .collect();
            let dynamic_fields: Vec<_> = type_def
                .fields
                .iter()
                .filter(|field| is_dynamic_field(field))
                .collect();
            for field in fixed_fields {
                out.push_str(&decode_field_expr(
                    &to_camel_case(&field.name),
                    &field.ty,
                    field.codec.as_ref(),
                    1,
                    &idl.types,
                ));
            }
            for field in &dynamic_fields {
                out.push_str(&decode_dynamic_header(
                    &to_camel_case(&field.name),
                    &field.ty,
                    field.codec.as_ref(),
                    1,
                ));
            }
            for field in dynamic_fields {
                out.push_str(&decode_dynamic_tail(
                    &to_camel_case(&field.name),
                    &field.ty,
                    field.codec.as_ref(),
                    1,
                    &idl.types,
                ));
            }
            let field_assigns: Vec<String> = type_def
                .fields
                .iter()
                .map(|f| {
                    let pascal = snake_to_pascal(&f.name);
                    let camel = to_camel_case(&f.name);
                    format!("\t\t{}: {},", pascal, camel)
                })
                .collect();
            out.push_str("\tif err := decoder.finish(); err != nil { return nil, err }\n");
            writeln!(out, "\treturn &{} {{", type_def.name).unwrap();
            for a in &field_assigns {
                writeln!(out, "{}", a).unwrap();
            }
            out.push_str("\t}, nil\n");
            out.push_str("}\n\n");
        }
    }

    // Instruction input structs + builder functions
    for ix in &idl.instructions {
        let pascal_name = snake_to_pascal(&ix.name);

        // Input struct
        writeln!(out, "type {}Input struct {{", pascal_name).unwrap();
        for acc in &ix.accounts {
            if !acc.optional
                && matches!(
                    acc.resolver,
                    IdlResolver::Const { .. } | IdlResolver::Pda { .. }
                )
            {
                continue;
            }
            // Optional accounts are pointer inputs; a nil pointer is encoded as
            // the program id sentinel.
            let acc_ty = if acc.optional {
                "*solana.PublicKey"
            } else {
                "solana.PublicKey"
            };
            writeln!(out, "\t{} {}", snake_to_pascal(&acc.name), acc_ty).unwrap();
        }
        for seed in account_field_seed_inputs(ix, idl) {
            writeln!(
                out,
                "\t{} {}",
                account_field_seed_input_name(&seed.path, &seed.field),
                go_type(&seed.ty),
            )
            .unwrap();
        }
        for arg in &ix.args {
            writeln!(out, "\t{} {}", snake_to_pascal(&arg.name), go_arg_type(arg),).unwrap();
        }
        if ix.remaining_accounts.is_some() {
            out.push_str("\tRemainingAccounts []*solana.AccountMeta\n");
        }
        out.push_str("}\n\n");

        // Builder function
        writeln!(
            out,
            "func New{}Instruction(input *{}Input) *solana.GenericInstruction {{",
            pascal_name, pascal_name,
        )
        .unwrap();

        // Accounts
        out.push_str("\taccounts := []*solana.AccountMeta{}\n");
        if !ix.accounts.is_empty() {
            out.push_str("\taccountsMap := map[string]solana.PublicKey{}\n");
        }
        for acc in &ix.accounts {
            let key_expr = if acc.optional {
                format!(
                    "func() solana.PublicKey {{ if input.{n} != nil {{ return *input.{n} }}; \
                     return ProgramID }}()",
                    n = snake_to_pascal(&acc.name)
                )
            } else if let IdlResolver::Const { ref address } = acc.resolver {
                format!("solana.MustPublicKeyFromBase58(\"{}\")", address)
            } else if let IdlResolver::Pda { ref seeds, .. } = acc.resolver {
                let mut seed_exprs = Vec::new();
                for seed in seeds {
                    match seed {
                        IdlPdaSeed::Const { value } => {
                            seed_exprs.push(format!("[]byte{{{}}}", super::format_disc_hex(value)));
                        }
                        IdlPdaSeed::Account { path } => {
                            seed_exprs.push(format!(
                                "func() []byte {{ key := accountsMap[\"{}\"]; return key[:] }}()",
                                path
                            ));
                        }
                        IdlPdaSeed::AccountField {
                            path,
                            field,
                            account,
                            ..
                        } => {
                            let ty = account_field_type(idl, account, field);
                            seed_exprs.push(go_pda_seed_expr(
                                &format!("input.{}", account_field_seed_input_name(path, field)),
                                ty.as_ref(),
                            ));
                        }
                        IdlPdaSeed::Arg { path, ty, .. } => {
                            seed_exprs.push(go_pda_seed_expr(
                                &format!("input.{}", go_field_path(path)),
                                Some(ty),
                            ));
                        }
                    }
                }
                // Invalid seeds are programmer errors in generated PDA calls.
                format!(
                    "func() solana.PublicKey {{ addr, _, err := \
                     solana.FindProgramAddress([][]byte{{{}}}, ProgramID); if err != nil {{ \
                     panic(err) }}; return addr }}()",
                    seed_exprs.join(", ")
                )
            } else {
                format!("input.{}", snake_to_pascal(&acc.name))
            };

            writeln!(out, "\taccountsMap[\"{}\"] = {}", acc.name, key_expr).unwrap();
            let meta_expr = account_meta_expr(
                &format!("accountsMap[\"{}\"]", acc.name),
                acc.signer.is_true(),
                acc.writable.is_true(),
            );
            writeln!(out, "\taccounts = append(accounts, {})", meta_expr).unwrap();
        }

        if ix.remaining_accounts.is_some() {
            out.push_str("\taccounts = append(accounts, input.RemainingAccounts...)\n");
        }

        // Compact wire format:
        //   [disc][fixed fields][all dynamic prefixes][all dynamic data]
        let disc_var = format!("{}Discriminator", pascal_name);
        let has_dyn = ix.args.iter().any(is_direct_dynamic);
        if ix.args.is_empty() {
            writeln!(out, "\tdata := {}[:]", disc_var).unwrap();
        } else if !has_dyn {
            // Fixed-only path: simple inline serialisation.
            writeln!(out, "\tdata := make([]byte, 0, 256)").unwrap();
            writeln!(out, "\tdata = append(data, {}[:]...)", disc_var).unwrap();
            for arg in &ix.args {
                out.push_str(&serialize_field_expr(
                    &snake_to_pascal(&arg.name),
                    &arg.ty,
                    arg.codec.as_ref(),
                    &idl.types,
                ));
            }
        } else {
            // Compact 3-phase encoding.
            let fixed_args: Vec<_> = ix.args.iter().filter(|a| !is_direct_dynamic(a)).collect();
            let dyn_args: Vec<_> = ix.args.iter().filter(|a| is_direct_dynamic(a)).collect();

            writeln!(out, "\tdata := make([]byte, 0, 256)").unwrap();
            writeln!(out, "\tdata = append(data, {}[:]...)", disc_var).unwrap();

            // Phase 1: fixed fields
            for arg in &fixed_args {
                out.push_str(&serialize_field_expr(
                    &snake_to_pascal(&arg.name),
                    &arg.ty,
                    arg.codec.as_ref(),
                    &idl.types,
                ));
            }

            // Pre-encode dynamic slices and group all length prefixes.
            for arg in &dyn_args {
                let name = snake_to_pascal(&arg.name);
                let prefix_bytes = arg.codec.as_ref().map(|c| c.prefix_bytes()).unwrap_or(2);
                if is_optional_dynamic(&arg.ty) {
                    writeln!(out, "\tif input.{n} == nil {{", n = name).unwrap();
                    out.push_str("\t\tdata = append(data, 0)\n");
                    out.push_str("\t} else {\n");
                    out.push_str("\t\tdata = append(data, 1)\n");
                    out.push_str("\t}\n");
                    continue;
                }
                match dynamic_payload_type(&arg.ty).expect("dynamic arg payload") {
                    IdlType::Primitive(p) if p == "string" => {
                        // Pre-encode string bytes so we know the length.
                        writeln!(out, "\t_{n}Bytes := []byte(input.{n})", n = name,).unwrap();
                        match prefix_bytes {
                            1 => writeln!(
                                out,
                                "\tdata = append(data, byte(len(_{n}Bytes)))",
                                n = name,
                            )
                            .unwrap(),
                            2 => writeln!(
                                out,
                                "\t{{ var _buf [2]byte; binary.LittleEndian.PutUint16(_buf[:], \
                                 uint16(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                n = name,
                            )
                            .unwrap(),
                            4 => writeln!(
                                out,
                                "\t{{ var _buf [4]byte; binary.LittleEndian.PutUint32(_buf[:], \
                                 uint32(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                n = name,
                            )
                            .unwrap(),
                            _ => writeln!(
                                out,
                                "\t{{ var _buf [8]byte; binary.LittleEndian.PutUint64(_buf[:], \
                                 uint64(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                n = name,
                            )
                            .unwrap(),
                        }
                    }
                    IdlType::Vec { .. } => match prefix_bytes {
                        1 => {
                            writeln!(out, "\tdata = append(data, byte(len(input.{n})))", n = name,)
                                .unwrap()
                        }
                        2 => writeln!(
                            out,
                            "\t{{ var _buf [2]byte; binary.LittleEndian.PutUint16(_buf[:], \
                             uint16(len(input.{n}))); data = append(data, _buf[:]...) }}",
                            n = name,
                        )
                        .unwrap(),
                        4 => writeln!(
                            out,
                            "\t{{ var _buf [4]byte; binary.LittleEndian.PutUint32(_buf[:], \
                             uint32(len(input.{n}))); data = append(data, _buf[:]...) }}",
                            n = name,
                        )
                        .unwrap(),
                        _ => writeln!(
                            out,
                            "\t{{ var _buf [8]byte; binary.LittleEndian.PutUint64(_buf[:], \
                             uint64(len(input.{n}))); data = append(data, _buf[:]...) }}",
                            n = name,
                        )
                        .unwrap(),
                    },
                    _ => unreachable!(),
                }
            }

            // Phase 3: tail data
            for arg in &dyn_args {
                let name = snake_to_pascal(&arg.name);
                let prefix_bytes = arg.codec.as_ref().map(|c| c.prefix_bytes()).unwrap_or(2);
                let payload_ty = dynamic_payload_type(&arg.ty).expect("dynamic arg payload");
                let optional = is_optional_dynamic(&arg.ty);
                if optional {
                    writeln!(out, "\tif input.{n} != nil {{", n = name).unwrap();
                }
                let pad = if optional { "\t\t" } else { "\t" };
                let value = if optional {
                    format!("*input.{name}")
                } else {
                    format!("input.{name}")
                };
                match payload_ty {
                    IdlType::Primitive(p) if p == "string" => {
                        if optional {
                            writeln!(
                                out,
                                "{pad}_{n}Bytes := []byte({value})",
                                pad = pad,
                                n = name,
                                value = value
                            )
                            .unwrap();
                            match prefix_bytes {
                                1 => writeln!(
                                    out,
                                    "{pad}data = append(data, byte(len(_{n}Bytes)))",
                                    pad = pad,
                                    n = name
                                )
                                .unwrap(),
                                2 => writeln!(
                                    out,
                                    "{pad}{{ var _buf [2]byte; \
                                     binary.LittleEndian.PutUint16(_buf[:], \
                                     uint16(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                    pad = pad,
                                    n = name
                                )
                                .unwrap(),
                                4 => writeln!(
                                    out,
                                    "{pad}{{ var _buf [4]byte; \
                                     binary.LittleEndian.PutUint32(_buf[:], \
                                     uint32(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                    pad = pad,
                                    n = name
                                )
                                .unwrap(),
                                _ => writeln!(
                                    out,
                                    "{pad}{{ var _buf [8]byte; \
                                     binary.LittleEndian.PutUint64(_buf[:], \
                                     uint64(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                    pad = pad,
                                    n = name
                                )
                                .unwrap(),
                            }
                        }
                        writeln!(
                            out,
                            "{pad}data = append(data, _{n}Bytes...)",
                            pad = pad,
                            n = name
                        )
                        .unwrap();
                    }
                    IdlType::Vec { vec } => {
                        if optional {
                            match prefix_bytes {
                                1 => writeln!(
                                    out,
                                    "{pad}data = append(data, byte(len({value})))",
                                    pad = pad,
                                    value = value
                                )
                                .unwrap(),
                                2 => writeln!(
                                    out,
                                    "{pad}{{ var _buf [2]byte; \
                                     binary.LittleEndian.PutUint16(_buf[:], \
                                     uint16(len({value}))); data = append(data, _buf[:]...) }}",
                                    pad = pad,
                                    value = value
                                )
                                .unwrap(),
                                4 => writeln!(
                                    out,
                                    "{pad}{{ var _buf [4]byte; \
                                     binary.LittleEndian.PutUint32(_buf[:], \
                                     uint32(len({value}))); data = append(data, _buf[:]...) }}",
                                    pad = pad,
                                    value = value
                                )
                                .unwrap(),
                                _ => writeln!(
                                    out,
                                    "{pad}{{ var _buf [8]byte; \
                                     binary.LittleEndian.PutUint64(_buf[:], \
                                     uint64(len({value}))); data = append(data, _buf[:]...) }}",
                                    pad = pad,
                                    value = value
                                )
                                .unwrap(),
                            }
                        }
                        writeln!(
                            out,
                            "{pad}for _, item := range {value} {{",
                            pad = pad,
                            value = value
                        )
                        .unwrap();
                        writeln!(out, "{pad}\t{}", go_vec_item_append(vec, "item"), pad = pad)
                            .unwrap();
                        writeln!(out, "{pad}}}", pad = pad).unwrap();
                    }
                    _ => unreachable!(),
                }
                if optional {
                    out.push_str("\t}\n");
                }
            }
        }

        out.push_str("\treturn solana.NewInstruction(ProgramID, accounts, data)\n");
        out.push_str("}\n\n");
    }

    // Event decoder
    if has_events {
        out.push_str("type DecodedEvent struct {\n");
        out.push_str("\tName string\n");
        out.push_str("\tData interface{}\n");
        out.push_str("}\n\n");

        out.push_str("func DecodeEvent(data []byte) (*DecodedEvent, error) {\n");
        for ev in &idl.events {
            let name = snake_to_pascal(&ev.name);
            let disc_len = ev.discriminator.len();
            let type_def = idl.types.iter().find(|t| t.name == ev.name);
            writeln!(
                out,
                "\tif len(data) >= {} && bytes.Equal(data[:{}], {}EventDiscriminator[:]) {{",
                disc_len, disc_len, name,
            )
            .unwrap();
            if let Some(td) = type_def {
                if td.fields.is_empty() {
                    writeln!(
                        out,
                        "\t\tif len(data) != {} {{ return nil, errors.New(\"trailing bytes\") \
                         }}\n\t\treturn &DecodedEvent{{Name: \"{}\", Data: nil}}, nil",
                        disc_len, ev.name
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "\t\tvalue, err := Decode{}(data[{}:])\n\t\tif err != nil {{ return nil, \
                         err }}\n\t\treturn &DecodedEvent{{Name: \"{}\", Data: value}}, nil",
                        ev.name, disc_len, ev.name,
                    )
                    .unwrap();
                }
            } else {
                writeln!(
                    out,
                    "\t\tif len(data) != {} {{ return nil, errors.New(\"trailing bytes\") \
                     }}\n\t\treturn &DecodedEvent{{Name: \"{}\", Data: nil}}, nil",
                    disc_len, ev.name
                )
                .unwrap();
            }
            out.push_str("\t}\n");
        }
        out.push_str("\treturn nil, nil\n");
        out.push_str("}\n\n");
    }

    Ok(out)
}

pub fn generate_go_mod_for_program(model: &ProgramModel<'_>) -> String {
    generate_go_mod(model.identity.go_package.as_str())
}

/// Generate go.mod content.
pub fn generate_go_mod(module_name: &str) -> String {
    format!(
        r#"module {}

go 1.21

require github.com/gagliardetto/solana-go v1.12.0
"#,
        module_name,
    )
}

fn go_type(ty: &IdlType) -> String {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => "bool".to_string(),
            "u8" => "uint8".to_string(),
            "i8" => "int8".to_string(),
            "u16" => "uint16".to_string(),
            "i16" => "int16".to_string(),
            "u32" => "uint32".to_string(),
            "i32" => "int32".to_string(),
            "u64" => "uint64".to_string(),
            "i64" => "int64".to_string(),
            "u128" => "[16]byte".to_string(),
            "i128" => "[16]byte".to_string(),
            "f32" => "float32".to_string(),
            "f64" => "float64".to_string(),
            "pubkey" => "solana.PublicKey".to_string(),
            "string" => "string".to_string(),
            _ => "[]byte".to_string(),
        },
        IdlType::Option { option } => format!("*{}", go_type(option)),
        IdlType::Vec { vec } => format!("[]{}", go_type(vec)),
        IdlType::Array {
            array: (_inner, size),
        } => format!("[{}]byte", size),
        IdlType::Defined { defined } => defined.name.clone(),
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in Go codegen", generic)
        }
    }
}

fn go_arg_type(arg: &IdlArg) -> String {
    if arg.codec.is_some() {
        if let IdlType::Option { option } = &arg.ty {
            if let IdlType::Vec { vec } = option.as_ref() {
                return format!("*[]{}", go_type(vec));
            }
        }
        if let IdlType::Vec { vec } = &arg.ty {
            return format!("[]{}", go_type(vec));
        }
    }
    go_type(&arg.ty)
}

fn account_meta_expr(key_expr: &str, signer: bool, writable: bool) -> String {
    let mut s = format!("solana.Meta({})", key_expr);
    if writable {
        s.push_str(".WRITE()");
    }
    if signer {
        s.push_str(".SIGNER()");
    }
    s
}

/// Returns `true` if the arg is a top-level dynamic type (string with codec or
/// Vec with codec). These require compact 3-phase encoding at the instruction
/// level.
fn is_direct_dynamic(arg: &IdlArg) -> bool {
    arg.codec.is_some() && dynamic_payload_type(&arg.ty).is_some()
}

fn is_dynamic_field(field: &IdlFieldDef) -> bool {
    field.codec.is_some() && dynamic_payload_type(&field.ty).is_some()
}

fn dynamic_payload_type(ty: &IdlType) -> Option<&IdlType> {
    match ty {
        IdlType::Primitive(p) if p == "string" => Some(ty),
        IdlType::Vec { .. } => Some(ty),
        IdlType::Option { option } => dynamic_payload_type(option),
        _ => None,
    }
}

fn is_optional_dynamic(ty: &IdlType) -> bool {
    matches!(ty, IdlType::Option { option } if dynamic_payload_type(option).is_some())
}

fn go_vec_item_append(item: &IdlType, source: &str) -> String {
    match item {
        IdlType::Primitive(p) if p == "pubkey" => format!("data = append(data, {source}[:]...)"),
        IdlType::Primitive(p) => {
            let width = primitive_size(p);
            match width {
                1 => format!("data = append(data, byte({source}))"),
                2 => format!(
                    "{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], uint16({source})); \
                     data = append(data, buf[:]...) }}"
                ),
                4 => format!(
                    "{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], uint32({source})); \
                     data = append(data, buf[:]...) }}"
                ),
                8 => format!(
                    "{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], uint64({source})); \
                     data = append(data, buf[:]...) }}"
                ),
                _ => format!("data = append(data, {source}[:]...)"),
            }
        }
        _ => format!("data = append(data, {source}...)"),
    }
}

fn primitive_size(p: &str) -> usize {
    match p {
        "bool" | "u8" | "i8" => 1,
        "u16" | "i16" => 2,
        "u32" | "i32" | "f32" => 4,
        "u64" | "i64" | "f64" => 8,
        "pubkey" => 32,
        "u128" | "i128" => 16,
        _ => 1,
    }
}

fn serialize_field_expr(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    types: &[IdlTypeDef],
) -> String {
    // Handle dynamic string with codec
    if let IdlType::Primitive(p) = ty {
        if p == "string" {
            if let Some(c) = codec {
                let prefix_bytes = c.prefix_bytes();
                return match prefix_bytes {
                    1 => format!(
                        "\tdata = append(data, byte(len([]byte(input.{n}))))\n\tdata = \
                         append(data, []byte(input.{n})...)\n",
                        n = name,
                    ),
                    2 => format!(
                        "\t{{ b := []byte(input.{n}); var buf [2]byte; \
                         binary.LittleEndian.PutUint16(buf[:], uint16(len(b))); data = \
                         append(data, buf[:]...); data = append(data, b...) }}\n",
                        n = name,
                    ),
                    4 => format!(
                        "\t{{ b := []byte(input.{n}); var buf [4]byte; \
                         binary.LittleEndian.PutUint32(buf[:], uint32(len(b))); data = \
                         append(data, buf[:]...); data = append(data, b...) }}\n",
                        n = name,
                    ),
                    _ => format!(
                        "\t{{ b := []byte(input.{n}); var buf [8]byte; \
                         binary.LittleEndian.PutUint64(buf[:], uint64(len(b))); data = \
                         append(data, buf[:]...); data = append(data, b...) }}\n",
                        n = name,
                    ),
                };
            }
        }
    }

    // Handle Vec with codec
    if let IdlType::Vec { .. } = ty {
        if let Some(c) = codec {
            let prefix_bytes = c.prefix_bytes();
            return match prefix_bytes {
                1 => format!(
                    "\tdata = append(data, byte(len(input.{n})))\n\tdata = append(data, \
                     input.{n}...)\n",
                    n = name,
                ),
                2 => format!(
                    "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], \
                     uint16(len(input.{n}))); data = append(data, buf[:]...); data = append(data, \
                     input.{n}...) }}\n",
                    n = name,
                ),
                4 => format!(
                    "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], \
                     uint32(len(input.{n}))); data = append(data, buf[:]...); data = append(data, \
                     input.{n}...) }}\n",
                    n = name,
                ),
                _ => format!(
                    "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], \
                     uint64(len(input.{n}))); data = append(data, buf[:]...); data = append(data, \
                     input.{n}...) }}\n",
                    n = name,
                ),
            };
        }
    }

    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!(
                "\tif input.{n} {{\n\t\tdata = append(data, 1)\n\t}} else {{\n\t\tdata = \
                 append(data, 0)\n\t}}\n",
                n = name,
            ),
            "u8" => format!("\tdata = append(data, input.{})\n", name),
            "i8" => format!("\tdata = append(data, byte(input.{}))\n", name),
            "u16" => format!(
                "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], input.{n}); data = \
                 append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i16" => format!(
                "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], uint16(input.{n})); \
                 data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], input.{n}); data = \
                 append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], uint32(input.{n})); \
                 data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.{n}); data = \
                 append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], uint64(input.{n})); \
                 data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u128" | "i128" => format!("\tdata = append(data, input.{}[:]...)\n", name,),
            "f32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], \
                 math.Float32bits(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "f64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], \
                 math.Float64bits(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "pubkey" => format!("\tdata = append(data, input.{}[:]...)\n", name,),
            "string" => format!(
                "\t{{ b := []byte(input.{n}); var buf [4]byte; \
                 binary.LittleEndian.PutUint32(buf[:], uint32(len(b))); data = append(data, \
                 buf[:]...); data = append(data, b...) }}\n",
                n = name,
            ),
            _ => format!("\tdata = append(data, input.{}...)\n", name),
        },
        IdlType::Option { option } => {
            let inner = serialize_field_expr(&format!("(*input.{})", name), option, None, types);
            format!(
                "\tif input.{n} == nil {{\n\t\tdata = append(data, 0)\n\t}} else {{\n\t\tdata = \
                 append(data, 1)\n{inner}\t}}\n",
                n = name,
                inner = inner,
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == defined.name) {
                let mut result = String::new();
                for field in &td.fields {
                    result.push_str(&serialize_field_expr(
                        &format!("{}.{}", name, snake_to_pascal(&field.name)),
                        &field.ty,
                        field.codec.as_ref(),
                        types,
                    ));
                }
                result
            } else {
                format!("\tdata = append(data, input.{}...)\n", name)
            }
        }
        IdlType::Vec { .. } => {
            // Vec without codec uses a Borsh-style u32 prefix.
            format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], \
                 uint32(len(input.{n}))); data = append(data, buf[:]...); data = append(data, \
                 input.{n}...) }}\n",
                n = name,
            )
        }
        IdlType::Array {
            array: (_inner, _size),
        } => {
            format!("\tdata = append(data, input.{}[:]...)\n", name)
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in Go codegen", generic)
        }
    }
}

fn decode_dynamic_header(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
) -> String {
    let t = "\t".repeat(depth);
    if is_optional_dynamic(ty) {
        return format!(
            "{t}{name}Tag := decoder.u8()\n{t}if {name}Tag > 1 {{ decoder.fail(\"invalid option \
             tag\") }}\n"
        );
    }
    let width = codec.expect("dynamic field codec").prefix_bytes();
    format!("{t}{name}Len := decoder.length({width})\n")
}

fn decode_dynamic_tail(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
    types: &[IdlTypeDef],
) -> String {
    let t = "\t".repeat(depth);
    if let IdlType::Option { option } = ty {
        let value = decode_dynamic_value(name, option, codec, depth + 1, false, types);
        return format!(
            "{t}var {name} *{value_ty}\n{t}if {name}Tag == 1 {{\n{value}{t}\t{name} = \
             &{name}Value\n{t}}}\n",
            value_ty = go_type(option),
        );
    }
    decode_dynamic_value(name, ty, codec, depth, true, types)
}

fn decode_dynamic_value(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
    length_is_known: bool,
    types: &[IdlTypeDef],
) -> String {
    let t = "\t".repeat(depth);
    let len_name = if length_is_known {
        format!("{name}Len")
    } else {
        format!("{name}ValueLen")
    };
    let prefix = if length_is_known {
        String::new()
    } else {
        let width = codec.expect("dynamic field codec").prefix_bytes();
        format!("{t}{len_name} := decoder.length({width})\n")
    };
    let value_name = if length_is_known {
        name.to_string()
    } else {
        format!("{name}Value")
    };
    match ty {
        IdlType::Primitive(primitive) if primitive == "string" => {
            format!("{prefix}{t}{value_name} := decoder.string({len_name})\n")
        }
        IdlType::Vec { vec } => {
            let item = decode_field_expr("item", vec, None, depth + 1, types);
            format!(
                "{prefix}{t}if {len_name} > maxDecodeElements {{ decoder.fail(\"element count \
                 exceeds limit\") }}\n{t}{value_name} := make([]{item_ty}, 0, min({len_name}, \
                 4096))\n{t}for i := 0; i < {len_name} && decoder.err == nil; i++ \
                 {{\n{item}{t}\t{value_name} = append({value_name}, item)\n{t}}}\n",
                item_ty = go_type(vec),
            )
        }
        _ => format!("{t}decoder.fail(\"invalid dynamic field\")\n"),
    }
}

fn decode_field_expr(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
    types: &[IdlTypeDef],
) -> String {
    let t = "\t".repeat(depth);

    // Handle dynamic string with codec
    if let IdlType::Primitive(p) = ty {
        if p == "string" {
            if let Some(c) = codec {
                let prefix_bytes = c.prefix_bytes();
                return format!(
                    "{t}{name}Len := decoder.length({prefix_bytes})\n{t}{name} := \
                     decoder.string({name}Len)\n"
                );
            }
        }
    }

    // Handle Vec with codec
    if let IdlType::Vec { vec } = ty {
        if let Some(c) = codec {
            let prefix_bytes = c.prefix_bytes();
            let item = decode_field_expr("item", vec, None, depth + 1, types);
            return format!(
                "{t}{name}Len := decoder.elements({prefix_bytes})\n{t}{name} := make([]{item_ty}, \
                 0, min({name}Len, 4096))\n{t}for i := 0; i < {name}Len && decoder.err == nil; \
                 i++ {{\n{item}{t}\t{name} = append({name}, item)\n{t}}}\n",
                item_ty = go_type(vec),
            );
        }
    }

    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!("{t}{name} := decoder.bool()\n"),
            "u8" => format!("{t}{name} := decoder.u8()\n"),
            "i8" => format!("{t}{name} := int8(decoder.u8())\n"),
            "u16" => format!("{t}{name} := decoder.u16()\n"),
            "i16" => format!("{t}{name} := int16(decoder.u16())\n"),
            "u32" => format!("{t}{name} := decoder.u32()\n"),
            "i32" => format!("{t}{name} := int32(decoder.u32())\n"),
            "u64" => format!("{t}{name} := decoder.u64()\n"),
            "i64" => format!("{t}{name} := int64(decoder.u64())\n"),
            "u128" | "i128" => {
                format!("{t}var {name} [16]byte\n{t}copy({name}[:], decoder.take(16))\n",)
            }
            "f32" => format!("{t}{name} := math.Float32frombits(decoder.u32())\n"),
            "f64" => format!("{t}{name} := math.Float64frombits(decoder.u64())\n"),
            "pubkey" => {
                format!("{t}var {name} solana.PublicKey\n{t}copy({name}[:], decoder.take(32))\n",)
            }
            "string" => {
                // Plain string without codec uses a Borsh-style u32 prefix.
                format!(
                    "{t}{name}Len := decoder.length(4)\n{t}{name} := decoder.string({name}Len)\n",
                )
            }
            _ => format!(
                "{t}decoder.fail(\"unsupported field type\")\n{t}var {name} {ty}\n",
                ty = go_type(ty),
            ),
        },
        IdlType::Vec { vec } => {
            // Vec without codec uses a Borsh-style u32 prefix.
            let item = decode_field_expr("item", vec, None, depth + 1, types);
            format!(
                "{t}{name}Len := decoder.elements(4)\n{t}{name} := make([]{item_ty}, 0, \
                 min({name}Len, 4096))\n{t}for i := 0; i < {name}Len && decoder.err == nil; i++ \
                 {{\n{item}{t}\t{name} = append({name}, item)\n{t}}}\n",
                item_ty = go_type(vec),
            )
        }
        IdlType::Array {
            array: (_inner, size),
        } => {
            format!("{t}var {name} [{size}]byte\n{t}copy({name}[:], decoder.take({size}))\n",)
        }
        IdlType::Option { option } => {
            let inner = decode_field_expr(&format!("{}_val", name), option, codec, depth, types);
            format!(
                "{t}var {name} *{ty}\n{t}{name}Tag := decoder.u8()\n{t}if {name}Tag == 1 \
                 {{\n{inner}{t}\t{name} = &{name}_val\n{t}}} else if {name}Tag != 0 \
                 {{\n{t}\tdecoder.fail(\"invalid option tag\")\n{t}}}\n",
                ty = go_type(option),
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == defined.name) {
                let mut result = String::new();
                for field in &td.fields {
                    result.push_str(&decode_field_expr(
                        &to_camel_case(&field.name),
                        &field.ty,
                        field.codec.as_ref(),
                        depth,
                        types,
                    ));
                }
                let field_assigns: Vec<String> = td
                    .fields
                    .iter()
                    .map(|f| format!("{}: {},", snake_to_pascal(&f.name), to_camel_case(&f.name)))
                    .collect();
                result.push_str(&format!(
                    "{t}{n} := {cls}{{\n",
                    t = t,
                    n = name,
                    cls = defined.name
                ));
                for a in &field_assigns {
                    result.push_str(&format!("{t}\t{a}\n", t = t, a = a));
                }
                result.push_str(&format!("{t}}}\n", t = t));
                result
            } else {
                format!(
                    "{t}decoder.fail(\"unknown defined type\")\n{t}var {name} {ty}\n",
                    ty = defined.name,
                )
            }
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in Go codegen", generic)
        }
    }
}

struct AccountFieldSeedInput {
    path: String,
    field: String,
    ty: IdlType,
}

fn account_field_seed_inputs(
    ix: &crate::types::IdlInstruction,
    idl: &Idl,
) -> Vec<AccountFieldSeedInput> {
    let mut inputs = Vec::new();
    for acc in &ix.accounts {
        if acc.optional {
            continue;
        }
        let IdlResolver::Pda { seeds, .. } = &acc.resolver else {
            continue;
        };
        for seed in seeds {
            let IdlPdaSeed::AccountField {
                path,
                account,
                field,
            } = seed
            else {
                continue;
            };
            if inputs
                .iter()
                .any(|input: &AccountFieldSeedInput| input.path == *path && input.field == *field)
            {
                continue;
            }
            if let Some(ty) = account_field_type(idl, account, field) {
                inputs.push(AccountFieldSeedInput {
                    path: path.clone(),
                    field: field.clone(),
                    ty,
                });
            }
        }
    }
    inputs
}

fn account_field_type(idl: &Idl, account: &str, field: &str) -> Option<IdlType> {
    let mut current_account = account.to_string();
    let mut field_ty = None;

    for segment in field.split('.') {
        let type_def = idl.types.iter().find(|ty| ty.name == current_account)?;
        let field_def = type_def.fields.iter().find(|f| f.name == segment)?;
        field_ty = Some(field_def.ty.clone());
        if let IdlType::Defined { defined } = &field_def.ty {
            current_account = defined.name.clone();
        }
    }

    field_ty
}

fn account_field_seed_input_name(path: &str, field: &str) -> String {
    format!(
        "{}{}Seed",
        snake_to_pascal(path),
        field
            .split('.')
            .map(snake_to_pascal)
            .collect::<Vec<_>>()
            .join("")
    )
}

fn go_pda_seed_expr(expr: &str, ty: Option<&IdlType>) -> String {
    match ty {
        Some(IdlType::Primitive(p)) => match p.as_str() {
            "pubkey" => format!("func() []byte {{ key := {expr}; return key[:] }}()"),
            "bool" => format!(
                "func() []byte {{ if {expr} {{ return []byte{{1}} }}; return []byte{{0}} }}()"
            ),
            "u8" | "i8" => format!("[]byte{{byte({expr})}}"),
            "u16" => format!(
                "func() []byte {{ b := make([]byte, 2); binary.LittleEndian.PutUint16(b, {expr}); \
                 return b }}()"
            ),
            "i16" => format!(
                "func() []byte {{ b := make([]byte, 2); binary.LittleEndian.PutUint16(b, \
                 uint16({expr})); return b }}()"
            ),
            "u32" => format!(
                "func() []byte {{ b := make([]byte, 4); binary.LittleEndian.PutUint32(b, {expr}); \
                 return b }}()"
            ),
            "i32" => format!(
                "func() []byte {{ b := make([]byte, 4); binary.LittleEndian.PutUint32(b, \
                 uint32({expr})); return b }}()"
            ),
            "u64" => format!(
                "func() []byte {{ b := make([]byte, 8); binary.LittleEndian.PutUint64(b, {expr}); \
                 return b }}()"
            ),
            "i64" => format!(
                "func() []byte {{ b := make([]byte, 8); binary.LittleEndian.PutUint64(b, \
                 uint64({expr})); return b }}()"
            ),
            "u128" | "i128" => format!("func() []byte {{ b := {expr}; return b[:] }}()"),
            _ => expr.to_string(),
        },
        Some(IdlType::Array { .. }) => format!("{expr}[:]"),
        _ => expr.to_string(),
    }
}
