//! Checked-in compute-unit and binary-size budgets.
//!
//! A budget file (`quasar-budget.toml` by default) records ceilings for a
//! program's total CU, its hottest functions, and its binary size.
//! `--write-budget` bootstraps or refreshes the file from a profile run;
//! `--check-budget` asserts against it and exits non-zero on any violation.

use {
    crate::aggregate::ProfileResult,
    serde::{Deserialize, Serialize},
    std::{
        collections::BTreeMap,
        fmt, fs, io,
        path::{Path, PathBuf},
    },
};

pub const DEFAULT_BUDGET_FILE: &str = "quasar-budget.toml";

/// Functions below this share of total CU are left out of a generated budget:
/// they churn with every inlining decision and drown the entries that matter.
const MIN_FUNCTION_SHARE: f64 = 0.01;

const HEADER: &str = "\
# Quasar compute-unit and binary-size budget.
#
# Generated by `quasar profile --write-budget`. Check this file in and enforce
# it with `quasar profile --check-budget`, which exits non-zero on violations.
#
# These ceilings are static: the profiler sums the cost of every instruction in
# the program image, which answers \"how expensive is this code\" rather than
# \"how many CU does this transaction burn\". The runtime figure depends on the
# branches a given instruction actually takes, so it is measured in tests, not
# here. The two are different questions; budget both.
#
# `binary_size` is the size of the profiled ELF. When `quasar profile` builds
# for you that is the debug-symbol artifact in target/profile/, not the
# stripped target/deploy/ upload. Pass an explicit ELF path to budget that one.
";

/// The parsed contents of a budget file.
#[derive(Debug, Default, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Budget {
    #[serde(default)]
    pub programs: BTreeMap<String, ProgramBudget>,
}

/// Ceilings for a single program.
#[derive(Debug, Default, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProgramBudget {
    #[serde(default)]
    pub total_cu: Option<u64>,
    #[serde(default)]
    pub binary_size: Option<u64>,
    #[serde(default)]
    pub functions: BTreeMap<String, u64>,
}

/// What a profile run actually measured.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Measurement {
    pub program: String,
    pub total_cu: u64,
    pub binary_size: u64,
    /// Self CU per function.
    pub functions: BTreeMap<String, u64>,
}

impl Measurement {
    pub(crate) fn from_profile(program: &str, binary_size: u64, result: &ProfileResult) -> Self {
        Self {
            program: program.to_string(),
            total_cu: result.total_cus,
            binary_size,
            functions: result.function_cus.iter().cloned().collect(),
        }
    }

    /// The ceilings a `--write-budget` run records for this measurement.
    pub fn to_budget(&self) -> ProgramBudget {
        let floor = (self.total_cu as f64 * MIN_FUNCTION_SHARE) as u64;
        ProgramBudget {
            total_cu: Some(self.total_cu),
            binary_size: Some(self.binary_size),
            functions: self
                .functions
                .iter()
                .filter(|(_, cu)| **cu >= floor && **cu > 0)
                .map(|(name, cu)| (name.clone(), *cu))
                .collect(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum Metric {
    TotalCu,
    BinarySize,
    Function,
}

impl Metric {
    pub fn label(self) -> &'static str {
        match self {
            Self::TotalCu => "total CU",
            Self::BinarySize => "binary size",
            Self::Function => "function",
        }
    }
}

/// One metric that exceeded its ceiling.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Violation {
    pub metric: Metric,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<String>,
    pub budget: u64,
    pub actual: u64,
    pub over: u64,
}

impl Violation {
    /// What the violation is about, e.g. `total CU` or `function Init::verify`.
    pub fn subject(&self) -> String {
        match &self.function {
            Some(name) => format!("{} {name}", self.metric.label()),
            None => self.metric.label().to_string(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MeasuredSummary {
    pub total_cu: u64,
    pub binary_size: u64,
}

/// The deterministic result of comparing a measurement against a budget.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Report {
    pub program: String,
    pub budget_path: String,
    pub ok: bool,
    pub measured: MeasuredSummary,
    /// Sorted: total CU, then binary size, then functions by name.
    pub violations: Vec<Violation>,
    /// Budgeted functions the profiler did not find (inlined or renamed).
    pub absent_functions: Vec<String>,
}

#[derive(Debug)]
pub enum BudgetError {
    Missing(PathBuf),
    Read { path: PathBuf, source: io::Error },
    Parse { path: PathBuf, source: String },
    UnknownProgram { path: PathBuf, program: String },
    Write { path: PathBuf, source: io::Error },
}

impl fmt::Display for BudgetError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Missing(path) => write!(
                f,
                "no budget file at {}. Bootstrap one with `quasar profile --write-budget`.",
                path.display()
            ),
            Self::Read { path, source } => {
                write!(f, "failed to read {}: {source}", path.display())
            }
            Self::Parse { path, source } => {
                write!(f, "failed to parse {}: {source}", path.display())
            }
            Self::UnknownProgram { path, program } => write!(
                f,
                "{} has no `[programs.{program}]` section. Add one with `quasar profile \
                 --write-budget`.",
                path.display()
            ),
            Self::Write { path, source } => {
                write!(f, "failed to write {}: {source}", path.display())
            }
        }
    }
}

impl std::error::Error for BudgetError {}

/// What a budget-flavoured profile run should do.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Run {
    /// `--write-budget`: record this measurement as the baseline.
    pub write: bool,
    /// `--check-budget`: assert against the recorded baseline.
    pub check: bool,
}

/// Apply a budget run: write the baseline, then check against it. Returns the
/// report when a check ran, `None` when only a write was asked for.
///
/// The returned report is data, not a verdict — the caller decides how to
/// present it and turns `!report.ok` into a non-zero exit.
pub fn apply(
    path: &Path,
    run: Run,
    measurement: &Measurement,
) -> Result<Option<Report>, BudgetError> {
    if run.write {
        let mut file = match load(path) {
            Ok(file) => file,
            // Bootstrapping is the whole point: absence is not an error here.
            Err(BudgetError::Missing(_)) => Budget::default(),
            Err(e) => return Err(e),
        };
        update(&mut file, measurement);
        save(path, &file)?;
    }

    if !run.check {
        return Ok(None);
    }

    load(path)?.check(path, measurement).map(Some)
}

/// Parse a budget file. Missing and malformed files are distinct errors.
pub fn load(path: &Path) -> Result<Budget, BudgetError> {
    let contents = match fs::read_to_string(path) {
        Ok(contents) => contents,
        Err(e) if e.kind() == io::ErrorKind::NotFound => {
            return Err(BudgetError::Missing(path.to_path_buf()))
        }
        Err(source) => {
            return Err(BudgetError::Read {
                path: path.to_path_buf(),
                source,
            })
        }
    };

    parse(&contents).map_err(|source| BudgetError::Parse {
        path: path.to_path_buf(),
        source,
    })
}

/// Parse budget TOML, reporting the underlying error (with span) on failure.
pub fn parse(contents: &str) -> Result<Budget, String> {
    toml::from_str(contents).map_err(|e| e.to_string())
}

/// Write `budget` to `path`, replacing any existing file.
pub fn save(path: &Path, budget: &Budget) -> Result<(), BudgetError> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).map_err(|source| BudgetError::Write {
                path: path.to_path_buf(),
                source,
            })?;
        }
    }
    fs::write(path, render(budget)).map_err(|source| BudgetError::Write {
        path: path.to_path_buf(),
        source,
    })
}

/// Merge `measurement` into `budget`, replacing only that program's ceilings.
///
/// Other programs in a workspace budget are left untouched.
pub fn update(budget: &mut Budget, measurement: &Measurement) {
    budget
        .programs
        .insert(measurement.program.clone(), measurement.to_budget());
}

/// Render a budget back to TOML. Output is sorted, so re-writing an unchanged
/// program produces a byte-identical file. User comments are not preserved.
pub fn render(budget: &Budget) -> String {
    let mut out = String::from(HEADER);

    for (program, entry) in &budget.programs {
        out.push_str(&format!("\n[programs.{}]\n", toml_key(program)));
        if let Some(total_cu) = entry.total_cu {
            out.push_str(&format!("total_cu = {total_cu}\n"));
        }
        if let Some(binary_size) = entry.binary_size {
            out.push_str(&format!("binary_size = {binary_size}\n"));
        }
        if !entry.functions.is_empty() {
            out.push_str(&format!("\n[programs.{}.functions]\n", toml_key(program)));
            for (name, cu) in &entry.functions {
                out.push_str(&format!("{} = {cu}\n", quote_key(name)));
            }
        }
    }

    out
}

impl Budget {
    /// Compare a measurement against this budget. Every violated metric is
    /// reported, not just the first.
    pub fn check(&self, path: &Path, measurement: &Measurement) -> Result<Report, BudgetError> {
        let entry =
            self.programs
                .get(&measurement.program)
                .ok_or_else(|| BudgetError::UnknownProgram {
                    path: path.to_path_buf(),
                    program: measurement.program.clone(),
                })?;

        let mut violations = Vec::new();
        if let Some(budget) = entry.total_cu {
            push_violation(
                &mut violations,
                Metric::TotalCu,
                None,
                budget,
                measurement.total_cu,
            );
        }
        if let Some(budget) = entry.binary_size {
            push_violation(
                &mut violations,
                Metric::BinarySize,
                None,
                budget,
                measurement.binary_size,
            );
        }

        let mut absent_functions = Vec::new();
        for (name, budget) in &entry.functions {
            match measurement.functions.get(name) {
                Some(actual) => push_violation(
                    &mut violations,
                    Metric::Function,
                    Some(name.clone()),
                    *budget,
                    *actual,
                ),
                None => absent_functions.push(name.clone()),
            }
        }

        Ok(Report {
            program: measurement.program.clone(),
            budget_path: path.display().to_string(),
            ok: violations.is_empty(),
            measured: MeasuredSummary {
                total_cu: measurement.total_cu,
                binary_size: measurement.binary_size,
            },
            violations,
            absent_functions,
        })
    }
}

fn push_violation(
    violations: &mut Vec<Violation>,
    metric: Metric,
    function: Option<String>,
    budget: u64,
    actual: u64,
) {
    if actual > budget {
        violations.push(Violation {
            metric,
            function,
            budget,
            actual,
            over: actual - budget,
        });
    }
}

fn toml_key(key: &str) -> String {
    let bare = !key.is_empty()
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-');
    if bare {
        key.to_string()
    } else {
        quote_key(key)
    }
}

fn quote_key(key: &str) -> String {
    format!("\"{}\"", key.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn measurement(total_cu: u64, binary_size: u64, functions: &[(&str, u64)]) -> Measurement {
        Measurement {
            program: "demo".to_string(),
            total_cu,
            binary_size,
            functions: functions
                .iter()
                .map(|(name, cu)| (name.to_string(), *cu))
                .collect(),
        }
    }

    #[test]
    fn parses_all_ceilings() {
        let budget = parse(
            r#"
[programs.demo]
total_cu = 1200
binary_size = 4096

[programs.demo.functions]
"<demo::Init as Accounts>::verify" = 300
"#,
        )
        .expect("valid budget");

        let demo = &budget.programs["demo"];
        assert_eq!(demo.total_cu, Some(1200));
        assert_eq!(demo.binary_size, Some(4096));
        assert_eq!(demo.functions["<demo::Init as Accounts>::verify"], 300);
    }

    #[test]
    fn parses_partial_and_empty_budgets() {
        let budget = parse("[programs.demo]\ntotal_cu = 10\n").expect("valid budget");
        let demo = &budget.programs["demo"];
        assert_eq!(demo.total_cu, Some(10));
        assert_eq!(demo.binary_size, None);
        assert!(demo.functions.is_empty());

        assert_eq!(parse("").expect("empty budget"), Budget::default());
    }

    #[test]
    fn rejects_malformed_budgets() {
        assert!(parse("[programs.demo]\ntotal_cu = \"lots\"\n").is_err());
        assert!(parse("[programs.demo]\ntotal_cu = -1\n").is_err());
        assert!(parse("[programs.demo]\ntotl_cu = 1\n").is_err());
        assert!(parse("[[programs.demo]]\n").is_err());
        assert!(parse("not toml at all").is_err());
    }

    #[test]
    fn missing_file_is_its_own_error() {
        let err = load(Path::new("does-not-exist-quasar-budget.toml")).unwrap_err();
        assert!(matches!(err, BudgetError::Missing(_)));
        assert!(err.to_string().contains("--write-budget"));
    }

    #[test]
    fn bootstrap_drops_functions_below_one_percent() {
        let m = measurement(1000, 2048, &[("hot", 500), ("warm", 10), ("cold", 3)]);
        let entry = m.to_budget();

        assert_eq!(entry.total_cu, Some(1000));
        assert_eq!(entry.binary_size, Some(2048));
        assert_eq!(entry.functions.len(), 2);
        assert_eq!(entry.functions["hot"], 500);
        assert_eq!(entry.functions["warm"], 10);
        assert!(!entry.functions.contains_key("cold"));
    }

    #[test]
    fn render_round_trips_and_is_stable() {
        let mut budget = Budget::default();
        update(
            &mut budget,
            &measurement(1000, 2048, &[("<demo::Init as Accounts>::verify", 500)]),
        );

        let rendered = render(&budget);
        assert_eq!(parse(&rendered).expect("round trip"), budget);
        assert_eq!(render(&parse(&rendered).unwrap()), rendered);
    }

    #[test]
    fn update_leaves_other_programs_alone() {
        let mut budget = parse("[programs.other]\ntotal_cu = 7\n").unwrap();
        update(&mut budget, &measurement(1000, 2048, &[]));

        assert_eq!(budget.programs["other"].total_cu, Some(7));
        assert_eq!(budget.programs["demo"].total_cu, Some(1000));
    }

    #[test]
    fn check_passes_when_every_metric_is_under() {
        let budget = parse(
            "[programs.demo]\ntotal_cu = 1000\nbinary_size = \
             2048\n\n[programs.demo.functions]\nhot = 500\n",
        )
        .unwrap();

        let report = budget
            .check(
                Path::new("quasar-budget.toml"),
                &measurement(1000, 2000, &[("hot", 499)]),
            )
            .expect("program is budgeted");

        assert!(report.ok);
        assert!(report.violations.is_empty());
        assert!(report.absent_functions.is_empty());
    }

    #[test]
    fn check_reports_every_violated_metric_in_order() {
        let budget = parse(
            "[programs.demo]\ntotal_cu = 1000\nbinary_size = \
             2048\n\n[programs.demo.functions]\nzeta = 10\nalpha = 20\n",
        )
        .unwrap();

        let report = budget
            .check(
                Path::new("quasar-budget.toml"),
                &measurement(1200, 4096, &[("zeta", 11), ("alpha", 25)]),
            )
            .expect("program is budgeted");

        assert!(!report.ok);
        let metrics: Vec<_> = report
            .violations
            .iter()
            .map(|v| (v.metric, v.function.as_deref(), v.over))
            .collect();
        assert_eq!(
            metrics,
            vec![
                (Metric::TotalCu, None, 200),
                (Metric::BinarySize, None, 2048),
                (Metric::Function, Some("alpha"), 5),
                (Metric::Function, Some("zeta"), 1),
            ]
        );
    }

    #[test]
    fn check_treats_equal_as_within_budget() {
        let budget = parse("[programs.demo]\ntotal_cu = 1000\n").unwrap();
        let report = budget
            .check(Path::new("b.toml"), &measurement(1000, 0, &[]))
            .unwrap();
        assert!(report.ok);
    }

    #[test]
    fn check_ignores_unbudgeted_metrics_and_functions() {
        let budget = parse("[programs.demo]\nbinary_size = 4096\n").unwrap();
        let report = budget
            .check(
                Path::new("b.toml"),
                &measurement(u64::MAX, 10, &[("unbudgeted", u64::MAX)]),
            )
            .unwrap();
        assert!(report.ok);
    }

    #[test]
    fn check_lists_budgeted_functions_that_vanished() {
        let budget =
            parse("[programs.demo]\n\n[programs.demo.functions]\ninlined_away = 10\n").unwrap();
        let report = budget
            .check(Path::new("b.toml"), &measurement(100, 0, &[("hot", 100)]))
            .unwrap();

        assert!(
            report.ok,
            "a function that no longer exists is not over budget"
        );
        assert_eq!(report.absent_functions, vec!["inlined_away".to_string()]);
    }

    #[test]
    fn check_fails_clearly_for_an_unbudgeted_program() {
        let budget = parse("[programs.other]\ntotal_cu = 1\n").unwrap();
        let err = budget
            .check(Path::new("quasar-budget.toml"), &measurement(1, 1, &[]))
            .unwrap_err();

        assert!(matches!(err, BudgetError::UnknownProgram { .. }));
        assert!(err.to_string().contains("[programs.demo]"));
    }

    /// A budget file in a throwaway directory, so `apply` exercises real I/O.
    fn scratch(contents: Option<&str>) -> (tempfile::TempDir, PathBuf) {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join(DEFAULT_BUDGET_FILE);
        if let Some(contents) = contents {
            fs::write(&path, contents).expect("seed budget");
        }
        (dir, path)
    }

    const WRITE: Run = Run {
        write: true,
        check: false,
    };
    const CHECK: Run = Run {
        write: false,
        check: true,
    };

    #[test]
    fn apply_bootstraps_a_budget_that_then_passes_its_own_check() {
        let (_dir, path) = scratch(None);
        let baseline = measurement(1000, 2048, &[("hot", 500)]);

        assert!(apply(&path, WRITE, &baseline)
            .expect("bootstrap from a missing file")
            .is_none());
        assert!(path.exists());

        let report = apply(&path, CHECK, &baseline)
            .expect("check against the file just written")
            .expect("check produces a report");
        assert!(report.ok, "a fresh baseline must not violate itself");
    }

    #[test]
    fn apply_check_fails_once_the_program_regresses() {
        let (_dir, path) = scratch(None);
        apply(&path, WRITE, &measurement(1000, 2048, &[("hot", 500)])).unwrap();

        let report = apply(&path, CHECK, &measurement(1001, 2048, &[("hot", 501)]))
            .unwrap()
            .unwrap();

        assert!(!report.ok);
        assert_eq!(report.violations.len(), 2, "{:?}", report.violations);
    }

    #[test]
    fn apply_rewrite_moves_the_ceiling_and_keeps_other_programs() {
        let (_dir, path) = scratch(Some("[programs.other]\ntotal_cu = 7\n"));
        apply(&path, WRITE, &measurement(1000, 2048, &[])).unwrap();
        apply(&path, WRITE, &measurement(1200, 2048, &[])).unwrap();

        let budget = load(&path).unwrap();
        assert_eq!(budget.programs["demo"].total_cu, Some(1200));
        assert_eq!(budget.programs["other"].total_cu, Some(7));
    }

    #[test]
    fn apply_write_and_check_together_always_passes() {
        let (_dir, path) = scratch(Some("[programs.demo]\ntotal_cu = 1\n"));
        let report = apply(
            &path,
            Run {
                write: true,
                check: true,
            },
            &measurement(1000, 2048, &[]),
        )
        .unwrap()
        .unwrap();

        assert!(report.ok, "the check must see the baseline just written");
    }

    #[test]
    fn apply_check_surfaces_missing_and_malformed_files() {
        let (_dir, missing) = scratch(None);
        assert!(matches!(
            apply(&missing, CHECK, &measurement(1, 1, &[])).unwrap_err(),
            BudgetError::Missing(_)
        ));

        let (_dir, malformed) = scratch(Some("[programs.demo]\ntotal_cu = \"lots\"\n"));
        assert!(matches!(
            apply(&malformed, CHECK, &measurement(1, 1, &[])).unwrap_err(),
            BudgetError::Parse { .. }
        ));
    }

    #[test]
    fn apply_write_refuses_to_clobber_a_malformed_file() {
        let (_dir, path) = scratch(Some("[programs.demo]\ntotl_cu = 1\n"));
        assert!(matches!(
            apply(&path, WRITE, &measurement(1, 1, &[])).unwrap_err(),
            BudgetError::Parse { .. }
        ));
        assert!(
            fs::read_to_string(&path).unwrap().contains("totl_cu"),
            "a typo must be reported, not silently overwritten"
        );
    }

    #[test]
    fn report_serializes_deterministically() {
        let budget = parse("[programs.demo]\ntotal_cu = 10\n").unwrap();
        let report = budget
            .check(Path::new("quasar-budget.toml"), &measurement(12, 0, &[]))
            .unwrap();

        let json = serde_json::to_string(&report).unwrap();
        assert_eq!(
            json,
            r#"{"program":"demo","budgetPath":"quasar-budget.toml","ok":false,"measured":{"totalCu":12,"binarySize":0},"violations":[{"metric":"totalCu","budget":10,"actual":12,"over":2}],"absentFunctions":[]}"#
        );
    }
}
