/* Code generated by quasar. DO NOT EDIT. */
#ifndef QUASAR_MULTISIG_CLIENT_H
#define QUASAR_MULTISIG_CLIENT_H

#include <caravel.h>

static const Pubkey QUASAR_MULTISIG_PROGRAM_ID = {{
    0x2d, 0x5b, 0x41, 0x3c, 0x65, 0x40, 0xde, 0x15,
    0x0c, 0x93, 0x73, 0x14, 0x4d, 0x51, 0x33, 0xca,
    0x4c, 0xb8, 0x30, 0xba, 0x0f, 0x75, 0x67, 0x16,
    0xac, 0xea, 0x0e, 0x50, 0xd7, 0x94, 0x35, 0xe5
}};

static const Pubkey QUASAR_MULTISIG_CREATE_RENT_ID = {{
    0x06, 0xa7, 0xd5, 0x17, 0x19, 0x2c, 0x5c, 0x51,
    0x21, 0x8c, 0xc9, 0x4c, 0x3d, 0x4a, 0xf1, 0x7f,
    0x58, 0xda, 0xee, 0x08, 0x9b, 0xa1, 0xfd, 0x44,
    0xe3, 0xdb, 0xd9, 0x8a, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_MULTISIG_CREATE_SYSTEM_PROGRAM_ID = {{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_MULTISIG_DEPOSIT_SYSTEM_PROGRAM_ID = {{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_MULTISIG_SET_LABEL_SYSTEM_PROGRAM_ID = {{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}};

static const Pubkey QUASAR_MULTISIG_EXECUTE_TRANSFER_SYSTEM_PROGRAM_ID = {{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}};

static const uint8_t QUASAR_MULTISIG_CREATE_DISC[] = {0x00};
static const uint8_t QUASAR_MULTISIG_DEPOSIT_DISC[] = {0x01};
static const uint8_t QUASAR_MULTISIG_SET_LABEL_DISC[] = {0x02};
static const uint8_t QUASAR_MULTISIG_EXECUTE_TRANSFER_DISC[] = {0x03};

static const uint8_t QUASAR_MULTISIG_MULTISIG_CONFIG_ACCOUNT_DISC[] = {0x01};

typedef struct {
    const uint8_t *data;
    uint64_t len;
    uint64_t offset;
} quasar_multisig_decoder_t;

static inline bool quasar_multisig_decoder_take(
    quasar_multisig_decoder_t *decoder,
    uint64_t size,
    const uint8_t **value
) {
    if (size > decoder->len - decoder->offset) return false;
    *value = &decoder->data[decoder->offset];
    decoder->offset += size;
    return true;
}

static inline bool quasar_multisig_decoder_uint(
    quasar_multisig_decoder_t *decoder,
    uint8_t width,
    uint64_t *value
) {
    const uint8_t *bytes;
    if (width != 1 && width != 2 && width != 4 && width != 8) return false;
    if (!quasar_multisig_decoder_take(decoder, width, &bytes)) return false;
    *value = 0;
    for (uint8_t i = 0; i < width; i++) *value |= ((uint64_t)bytes[i]) << (i * 8);
    return true;
}

static inline bool quasar_multisig_decoder_span(
    quasar_multisig_decoder_t *decoder,
    uint8_t width,
    uint32_t item_size,
    const uint8_t **value,
    uint32_t *count
) {
    uint64_t count64;
    if (!quasar_multisig_decoder_uint(decoder, width, &count64)) return false;
    if (count64 > ((uint32_t)-1)) return false;
    uint64_t byte_len = count64 * item_size;
    if (!quasar_multisig_decoder_take(decoder, byte_len, value)) return false;
    *count = (uint32_t)count64;
    return true;
}

static inline bool quasar_multisig_utf8_valid(const uint8_t *data, uint32_t len) {
    uint32_t i = 0;
    while (i < len) {
        uint8_t c = data[i++];
        if (c < 0x80) continue;
        uint32_t needed;
        uint32_t code;
        uint32_t minimum;
        if ((c & 0xe0) == 0xc0) { needed = 1; code = c & 0x1f; minimum = 0x80; }
        else if ((c & 0xf0) == 0xe0) { needed = 2; code = c & 0x0f; minimum = 0x800; }
        else if ((c & 0xf8) == 0xf0) { needed = 3; code = c & 0x07; minimum = 0x10000; }
        else return false;
        if (needed > len - i) return false;
        for (uint32_t j = 0; j < needed; j++) {
            uint8_t next = data[i++];
            if ((next & 0xc0) != 0x80) return false;
            code = (code << 6) | (next & 0x3f);
        }
        if (code < minimum || code > 0x10ffff || (code >= 0xd800 && code <= 0xdfff)) return false;
    }
    return true;
}

typedef struct {
    Pubkey creator;
    uint8_t threshold;
    uint8_t bump;
    const uint8_t *label;
    uint32_t label_len;
    const Pubkey *signers;
    uint32_t signers_len;
} quasar_multisig_multisig_config_t;

static inline bool quasar_multisig_multisig_config_decode(
    const uint8_t *data,
    uint64_t data_len,
    quasar_multisig_multisig_config_t *out
) {
    quasar_multisig_decoder_t decoder = { .data = data, .len = data_len, .offset = 0 };
    { const uint8_t *bytes; if (!quasar_multisig_decoder_take(&decoder, 32, &bytes)) return false; for (int i = 0; i < 32; i++) out->creator.bytes[i] = bytes[i]; }
    { uint64_t v; if (!quasar_multisig_decoder_uint(&decoder, 1, &v)) return false; out->threshold = (uint8_t)v; }
    { uint64_t v; if (!quasar_multisig_decoder_uint(&decoder, 1, &v)) return false; out->bump = (uint8_t)v; }
    { uint64_t count; if (!quasar_multisig_decoder_uint(&decoder, 1, &count) || count > ((uint32_t)-1)) return false; out->label_len = (uint32_t)count; }
    { uint64_t count; if (!quasar_multisig_decoder_uint(&decoder, 2, &count) || count > ((uint32_t)-1)) return false; out->signers_len = (uint32_t)count; }
    const uint8_t *label_bytes;
    if (!quasar_multisig_decoder_take(&decoder, (uint64_t)out->label_len * 1, &label_bytes)) return false;
    if (!quasar_multisig_utf8_valid(label_bytes, out->label_len)) return false;
    out->label = label_bytes;
    const uint8_t *signers_bytes;
    if (!quasar_multisig_decoder_take(&decoder, (uint64_t)out->signers_len * 32, &signers_bytes)) return false;
    out->signers = (const Pubkey *)signers_bytes;
    return decoder.offset == decoder.len;
}

typedef enum {
    QUASAR_MULTISIG_IX_OK = 0,
    QUASAR_MULTISIG_IX_ACCOUNT_BUFFER_TOO_SMALL,
    QUASAR_MULTISIG_IX_DATA_BUFFER_TOO_SMALL,
    QUASAR_MULTISIG_IX_LENGTH_OVERFLOW,
    QUASAR_MULTISIG_IX_PDA_DERIVATION_FAILED,
    QUASAR_MULTISIG_IX_PDA_KEY_BUFFER_TOO_SMALL
} quasar_multisig_ix_status_t;

typedef struct {
    quasar_multisig_ix_status_t status;
    uint64_t accounts_len;
    uint64_t data_len;
    uint64_t pda_keys_len;
    uint64_t pda_status;
} quasar_multisig_ix_result_t;

static inline bool quasar_multisig_ix_size_add(uint64_t *size, uint64_t amount) {
    if (amount > ((uint64_t)-1) - *size) return false;
    *size += amount;
    return true;
}

static inline bool quasar_multisig_ix_size_add_items(
    uint64_t *size,
    uint64_t count,
    uint64_t item_size
) {
    if (item_size != 0 && count > ((uint64_t)-1) / item_size) return false;
    return quasar_multisig_ix_size_add(size, count * item_size);
}

typedef struct {
    Pubkey *creator;
} quasar_multisig_create_accounts_t;

typedef struct {
    uint8_t threshold;
} quasar_multisig_create_args_t;

static inline quasar_multisig_ix_result_t quasar_multisig_create_ix(
    quasar_multisig_create_accounts_t *accounts,
    quasar_multisig_create_args_t *args,
    const AccountMeta *remaining,
    uint64_t remaining_len,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint64_t meta_buf_capacity,
    Pubkey *pda_key_buf,
    uint64_t pda_key_buf_capacity,
    uint8_t *data_buf,
    uint64_t data_buf_capacity
) {
    const uint64_t required_pda_keys = 1;
    if (remaining_len > ((uint64_t)-1) - 4) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_LENGTH_OVERFLOW, .accounts_len = (uint64_t)-1, .data_len = 0, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    uint64_t required_accounts = 4 + remaining_len;
    uint64_t required_data = 1;
    if (!quasar_multisig_ix_size_add(&required_data, 1)) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (meta_buf_capacity < required_accounts) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (pda_key_buf_capacity < required_pda_keys) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_KEY_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (data_buf_capacity < required_data) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    Pubkey derived_pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}; seeds[0].addr = s; seeds[0].len = 8; }
        seeds[1].addr = accounts->creator->bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_MULTISIG_PROGRAM_ID, &derived_pda_keys[0], &bump);
        if (pda_status != SUCCESS) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = derived_pda_keys[i];
    meta_buf[0] = meta_writable_signer(accounts->creator);
    meta_buf[1] = meta_writable(&pda_key_buf[0]);
    meta_buf[2] = meta_readonly((Pubkey *)&QUASAR_MULTISIG_CREATE_RENT_ID);
    meta_buf[3] = meta_readonly((Pubkey *)&QUASAR_MULTISIG_CREATE_SYSTEM_PROGRAM_ID);
    uint64_t off = 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_CREATE_DISC[i];
    data_buf[off++] = args->threshold;
    for (uint64_t i = 0; i < remaining_len; i++) meta_buf[4 + i] = remaining[i];
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = required_accounts;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_OK, .accounts_len = required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
}

typedef struct {
    Pubkey *depositor;
    Pubkey *config;
} quasar_multisig_deposit_accounts_t;

typedef struct {
    uint64_t amount;
} quasar_multisig_deposit_args_t;

static inline quasar_multisig_ix_result_t quasar_multisig_deposit_ix(
    quasar_multisig_deposit_accounts_t *accounts,
    quasar_multisig_deposit_args_t *args,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint64_t meta_buf_capacity,
    Pubkey *pda_key_buf,
    uint64_t pda_key_buf_capacity,
    uint8_t *data_buf,
    uint64_t data_buf_capacity
) {
    const uint64_t required_pda_keys = 1;
    uint64_t required_accounts = 4;
    uint64_t required_data = 1;
    if (!quasar_multisig_ix_size_add(&required_data, 8)) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (meta_buf_capacity < required_accounts) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (pda_key_buf_capacity < required_pda_keys) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_KEY_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (data_buf_capacity < required_data) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    Pubkey derived_pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x76, 0x61, 0x75, 0x6c, 0x74}; seeds[0].addr = s; seeds[0].len = 5; }
        seeds[1].addr = accounts->config->bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_MULTISIG_PROGRAM_ID, &derived_pda_keys[0], &bump);
        if (pda_status != SUCCESS) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = derived_pda_keys[i];
    meta_buf[0] = meta_writable_signer(accounts->depositor);
    meta_buf[1] = meta_readonly(accounts->config);
    meta_buf[2] = meta_writable(&pda_key_buf[0]);
    meta_buf[3] = meta_readonly((Pubkey *)&QUASAR_MULTISIG_DEPOSIT_SYSTEM_PROGRAM_ID);
    uint64_t off = 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_DEPOSIT_DISC[i];
    { uint64_t v = args->amount; for (int i = 0; i < 8; i++) { data_buf[off + i] = (uint8_t)(v >> (i * 8)); } off += 8; }
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = required_accounts;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_OK, .accounts_len = required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
}

typedef struct {
    Pubkey *creator;
} quasar_multisig_set_label_accounts_t;

typedef struct {
    const uint8_t *label;
    uint32_t label_len;
} quasar_multisig_set_label_args_t;

static inline quasar_multisig_ix_result_t quasar_multisig_set_label_ix(
    quasar_multisig_set_label_accounts_t *accounts,
    quasar_multisig_set_label_args_t *args,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint64_t meta_buf_capacity,
    Pubkey *pda_key_buf,
    uint64_t pda_key_buf_capacity,
    uint8_t *data_buf,
    uint64_t data_buf_capacity
) {
    const uint64_t required_pda_keys = 1;
    uint64_t required_accounts = 3;
    uint64_t required_data = 1;
    if (!quasar_multisig_ix_size_add(&required_data, 1)) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (!quasar_multisig_ix_size_add_items(&required_data, args->label_len, 1)) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (meta_buf_capacity < required_accounts) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (pda_key_buf_capacity < required_pda_keys) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_KEY_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (data_buf_capacity < required_data) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    Pubkey derived_pda_keys[1];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}; seeds[0].addr = s; seeds[0].len = 8; }
        seeds[1].addr = accounts->creator->bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_MULTISIG_PROGRAM_ID, &derived_pda_keys[0], &bump);
        if (pda_status != SUCCESS) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = derived_pda_keys[i];
    meta_buf[0] = meta_writable_signer(accounts->creator);
    meta_buf[1] = meta_writable(&pda_key_buf[0]);
    meta_buf[2] = meta_readonly((Pubkey *)&QUASAR_MULTISIG_SET_LABEL_SYSTEM_PROGRAM_ID);
    uint64_t off = 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_SET_LABEL_DISC[i];
    data_buf[off++] = (uint8_t)args->label_len;
    for (uint32_t i = 0; i < args->label_len; i++) data_buf[off++] = args->label[i];
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = required_accounts;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_OK, .accounts_len = required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
}

typedef struct {
    Pubkey *creator;
    Pubkey *recipient;
} quasar_multisig_execute_transfer_accounts_t;

typedef struct {
    uint64_t amount;
} quasar_multisig_execute_transfer_args_t;

static inline quasar_multisig_ix_result_t quasar_multisig_execute_transfer_ix(
    quasar_multisig_execute_transfer_accounts_t *accounts,
    quasar_multisig_execute_transfer_args_t *args,
    const AccountMeta *remaining,
    uint64_t remaining_len,
    Instruction *ix_out,
    AccountMeta *meta_buf,
    uint64_t meta_buf_capacity,
    Pubkey *pda_key_buf,
    uint64_t pda_key_buf_capacity,
    uint8_t *data_buf,
    uint64_t data_buf_capacity
) {
    const uint64_t required_pda_keys = 2;
    if (remaining_len > ((uint64_t)-1) - 5) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_LENGTH_OVERFLOW, .accounts_len = (uint64_t)-1, .data_len = 0, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    uint64_t required_accounts = 5 + remaining_len;
    uint64_t required_data = 1;
    if (!quasar_multisig_ix_size_add(&required_data, 8)) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_LENGTH_OVERFLOW, .accounts_len = required_accounts, .data_len = (uint64_t)-1, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (meta_buf_capacity < required_accounts) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_ACCOUNT_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (pda_key_buf_capacity < required_pda_keys) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_KEY_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    if (data_buf_capacity < required_data) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_DATA_BUFFER_TOO_SMALL, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
    Pubkey derived_pda_keys[2];
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}; seeds[0].addr = s; seeds[0].len = 8; }
        seeds[1].addr = accounts->creator->bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_MULTISIG_PROGRAM_ID, &derived_pda_keys[0], &bump);
        if (pda_status != SUCCESS) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    {
        SignerSeed seeds[2];
        { static const uint8_t s[] = {0x76, 0x61, 0x75, 0x6c, 0x74}; seeds[0].addr = s; seeds[0].len = 5; }
        seeds[1].addr = derived_pda_keys[0].bytes; seeds[1].len = 32;
        uint8_t bump;
        uint64_t pda_status = find_program_address(seeds, 2, &QUASAR_MULTISIG_PROGRAM_ID, &derived_pda_keys[1], &bump);
        if (pda_status != SUCCESS) return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_PDA_DERIVATION_FAILED, .accounts_len = required_accounts, .data_len = required_data, .pda_keys_len = required_pda_keys, .pda_status = pda_status };
    }
    for (uint64_t i = 0; i < required_pda_keys; i++) pda_key_buf[i] = derived_pda_keys[i];
    meta_buf[0] = meta_readonly(&pda_key_buf[0]);
    meta_buf[1] = meta_readonly(accounts->creator);
    meta_buf[2] = meta_writable(&pda_key_buf[1]);
    meta_buf[3] = meta_writable(accounts->recipient);
    meta_buf[4] = meta_readonly((Pubkey *)&QUASAR_MULTISIG_EXECUTE_TRANSFER_SYSTEM_PROGRAM_ID);
    uint64_t off = 0;
    for (uint64_t i = 0; i < 1; i++) data_buf[off++] = QUASAR_MULTISIG_EXECUTE_TRANSFER_DISC[i];
    { uint64_t v = args->amount; for (int i = 0; i < 8; i++) { data_buf[off + i] = (uint8_t)(v >> (i * 8)); } off += 8; }
    for (uint64_t i = 0; i < remaining_len; i++) meta_buf[5 + i] = remaining[i];
    ix_out->program_id = (Pubkey *)&QUASAR_MULTISIG_PROGRAM_ID;
    ix_out->accounts = meta_buf;
    ix_out->accounts_len = required_accounts;
    ix_out->data = data_buf;
    ix_out->data_len = off;
    return (quasar_multisig_ix_result_t){ .status = QUASAR_MULTISIG_IX_OK, .accounts_len = required_accounts, .data_len = off, .pda_keys_len = required_pda_keys, .pda_status = SUCCESS };
}

#define QUASAR_MULTISIG_ERR_ACCOUNTALREADYINITIALIZED 3001
#define QUASAR_MULTISIG_ERR_ACCOUNTNOTINITIALIZED 3000
#define QUASAR_MULTISIG_ERR_ACCOUNTNOTMUTABLE 3010
#define QUASAR_MULTISIG_ERR_ACCOUNTNOTRENTEXEMPT 3008
#define QUASAR_MULTISIG_ERR_ACCOUNTNOTSIGNER 3011
#define QUASAR_MULTISIG_ERR_ACCOUNTOWNEDBYWRONGPROGRAM 3009
#define QUASAR_MULTISIG_ERR_ADDRESSMISMATCH 3012
#define QUASAR_MULTISIG_ERR_COMPACTWRITERFIELDNOTSET 3014
#define QUASAR_MULTISIG_ERR_CONSTRAINTVIOLATION 3004
#define QUASAR_MULTISIG_ERR_DYNAMICFIELDTOOLONG 3013
#define QUASAR_MULTISIG_ERR_HASONEMISMATCH 3005
#define QUASAR_MULTISIG_ERR_INSUFFICIENTSPACE 3007
#define QUASAR_MULTISIG_ERR_INVALIDDISCRIMINATOR 3006
#define QUASAR_MULTISIG_ERR_INVALIDPDA 3002
#define QUASAR_MULTISIG_ERR_INVALIDRETURNDATA 3019
#define QUASAR_MULTISIG_ERR_INVALIDSEEDS 3003
#define QUASAR_MULTISIG_ERR_MISSINGRETURNDATA 3017
#define QUASAR_MULTISIG_ERR_REMAININGACCOUNTDUPLICATE 3016
#define QUASAR_MULTISIG_ERR_REMAININGACCOUNTSOVERFLOW 3015
#define QUASAR_MULTISIG_ERR_RETURNDATAFROMWRONGPROGRAM 3018

#endif /* QUASAR_MULTISIG_CLIENT_H */
