// Code generated by quasar. DO NOT EDIT.
package quasar_multisig

import (
	"errors"
	"encoding/binary"
	"unicode/utf8"

	solana "github.com/gagliardetto/solana-go"
)

var ProgramID = solana.MustPublicKeyFromBase58("44444444444444444444444444444444444444444444")

const maxDecodeElements = 10 * 1024 * 1024

type quasarDecoder struct {
	data []byte
	offset int
	err error
}

func (d *quasarDecoder) fail(message string) {
	if d.err == nil { d.err = errors.New(message) }
}

func (d *quasarDecoder) take(size int) []byte {
	if d.err != nil { return nil }
	if size < 0 || d.offset < 0 || size > len(d.data)-d.offset {
		d.fail("truncated input")
		return nil
	}
	end := d.offset + size
	value := d.data[d.offset:end]
	d.offset = end
	return value
}

func (d *quasarDecoder) length(width int) int {
	raw := d.take(width)
	if d.err != nil { return 0 }
	var value uint64
	switch width {
	case 1: value = uint64(raw[0])
	case 2: value = uint64(binary.LittleEndian.Uint16(raw))
	case 4: value = uint64(binary.LittleEndian.Uint32(raw))
	case 8: value = binary.LittleEndian.Uint64(raw)
	default: d.fail("invalid length prefix width"); return 0
	}
	if value > uint64(^uint(0)>>1) { d.fail("length overflows int"); return 0 }
	return int(value)
}

func (d *quasarDecoder) u8() uint8 {
	raw := d.take(1); if d.err != nil { return 0 }; return raw[0]
}

func (d *quasarDecoder) u16() uint16 {
	raw := d.take(2); if d.err != nil { return 0 }; return binary.LittleEndian.Uint16(raw)
}

func (d *quasarDecoder) u32() uint32 {
	raw := d.take(4); if d.err != nil { return 0 }; return binary.LittleEndian.Uint32(raw)
}

func (d *quasarDecoder) u64() uint64 {
	raw := d.take(8); if d.err != nil { return 0 }; return binary.LittleEndian.Uint64(raw)
}

func (d *quasarDecoder) elements(width int) int {
	count := d.length(width)
	if count > maxDecodeElements || count > len(d.data)-d.offset { d.fail("element count exceeds limit"); return 0 }
	return count
}

func (d *quasarDecoder) bool() bool {
	raw := d.u8()
	if d.err != nil { return false }
	if raw > 1 { d.fail("invalid bool"); return false }
	return raw == 1
}

func (d *quasarDecoder) string(size int) string {
	raw := d.take(size)
	if d.err != nil { return "" }
	if !utf8.Valid(raw) { d.fail("invalid UTF-8"); return "" }
	return string(raw)
}

func (d *quasarDecoder) finish() error {
	if d.err != nil { return d.err }
	if d.offset != len(d.data) { return errors.New("trailing bytes") }
	return nil
}

var CreateDiscriminator = [1]byte{0x00}
var DepositDiscriminator = [1]byte{0x01}
var SetLabelDiscriminator = [1]byte{0x02}
var ExecuteTransferDiscriminator = [1]byte{0x03}

var MultisigConfigAccountDiscriminator = [1]byte{0x01}

type MultisigConfig struct {
	Creator solana.PublicKey
	Threshold uint8
	Bump uint8
	Label string
	Signers []solana.PublicKey
}

func DecodeMultisigConfig(data []byte) (*MultisigConfig, error) {
	decoder := quasarDecoder{data: data}
	var creator solana.PublicKey
	copy(creator[:], decoder.take(32))
	threshold := decoder.u8()
	bump := decoder.u8()
	labelLen := decoder.length(1)
	signersLen := decoder.length(2)
	label := decoder.string(labelLen)
	if signersLen > maxDecodeElements { decoder.fail("element count exceeds limit") }
	signers := make([]solana.PublicKey, 0, min(signersLen, 4096))
	for i := 0; i < signersLen && decoder.err == nil; i++ {
		var item solana.PublicKey
		copy(item[:], decoder.take(32))
		signers = append(signers, item)
	}
	if err := decoder.finish(); err != nil { return nil, err }
	return &MultisigConfig {
		Creator: creator,
		Threshold: threshold,
		Bump: bump,
		Label: label,
		Signers: signers,
	}, nil
}

type CreateInput struct {
	Creator solana.PublicKey
	Threshold uint8
	RemainingAccounts []*solana.AccountMeta
}

func NewCreateInstruction(input *CreateInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{}
	accountsMap := map[string]solana.PublicKey{}
	accountsMap["creator"] = input.Creator
	accounts = append(accounts, solana.Meta(accountsMap["creator"]).WRITE().SIGNER())
	accountsMap["config"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}, func() []byte { key := accountsMap["creator"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["config"]).WRITE())
	accountsMap["rent"] = solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")
	accounts = append(accounts, solana.Meta(accountsMap["rent"]))
	accountsMap["systemProgram"] = solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	accounts = append(accounts, solana.Meta(accountsMap["systemProgram"]))
	accounts = append(accounts, input.RemainingAccounts...)
	data := make([]byte, 0, 256)
	data = append(data, CreateDiscriminator[:]...)
	data = append(data, input.Threshold)
	return solana.NewInstruction(ProgramID, accounts, data)
}

type DepositInput struct {
	Depositor solana.PublicKey
	Config solana.PublicKey
	Amount uint64
}

func NewDepositInstruction(input *DepositInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{}
	accountsMap := map[string]solana.PublicKey{}
	accountsMap["depositor"] = input.Depositor
	accounts = append(accounts, solana.Meta(accountsMap["depositor"]).WRITE().SIGNER())
	accountsMap["config"] = input.Config
	accounts = append(accounts, solana.Meta(accountsMap["config"]))
	accountsMap["vault"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x76, 0x61, 0x75, 0x6c, 0x74}, func() []byte { key := accountsMap["config"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["vault"]).WRITE())
	accountsMap["systemProgram"] = solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	accounts = append(accounts, solana.Meta(accountsMap["systemProgram"]))
	data := make([]byte, 0, 256)
	data = append(data, DepositDiscriminator[:]...)
	{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.Amount); data = append(data, buf[:]...) }
	return solana.NewInstruction(ProgramID, accounts, data)
}

type SetLabelInput struct {
	Creator solana.PublicKey
	Label string
}

func NewSetLabelInstruction(input *SetLabelInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{}
	accountsMap := map[string]solana.PublicKey{}
	accountsMap["creator"] = input.Creator
	accounts = append(accounts, solana.Meta(accountsMap["creator"]).WRITE().SIGNER())
	accountsMap["config"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}, func() []byte { key := accountsMap["creator"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["config"]).WRITE())
	accountsMap["systemProgram"] = solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	accounts = append(accounts, solana.Meta(accountsMap["systemProgram"]))
	data := make([]byte, 0, 256)
	data = append(data, SetLabelDiscriminator[:]...)
	_LabelBytes := []byte(input.Label)
	data = append(data, byte(len(_LabelBytes)))
	data = append(data, _LabelBytes...)
	return solana.NewInstruction(ProgramID, accounts, data)
}

type ExecuteTransferInput struct {
	Creator solana.PublicKey
	Recipient solana.PublicKey
	Amount uint64
	RemainingAccounts []*solana.AccountMeta
}

func NewExecuteTransferInstruction(input *ExecuteTransferInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{}
	accountsMap := map[string]solana.PublicKey{}
	accountsMap["config"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67}, func() []byte { key := accountsMap["creator"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["config"]))
	accountsMap["creator"] = input.Creator
	accounts = append(accounts, solana.Meta(accountsMap["creator"]))
	accountsMap["vault"] = func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x76, 0x61, 0x75, 0x6c, 0x74}, func() []byte { key := accountsMap["config"]; return key[:] }()}, ProgramID); if err != nil { panic(err) }; return addr }()
	accounts = append(accounts, solana.Meta(accountsMap["vault"]).WRITE())
	accountsMap["recipient"] = input.Recipient
	accounts = append(accounts, solana.Meta(accountsMap["recipient"]).WRITE())
	accountsMap["systemProgram"] = solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	accounts = append(accounts, solana.Meta(accountsMap["systemProgram"]))
	accounts = append(accounts, input.RemainingAccounts...)
	data := make([]byte, 0, 256)
	data = append(data, ExecuteTransferDiscriminator[:]...)
	{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.Amount); data = append(data, buf[:]...) }
	return solana.NewInstruction(ProgramID, accounts, data)
}
