//! Program runtime-environment macros.
//!
//! `no_alloc!`, `heap_alloc!`, and `panic_handler!` configure the program's
//! runtime environment (allocator and panic behavior). Instruction dispatch is
//! generated by `#[program]` (quasar-derive's `program/dispatch.rs`), not by a
//! hand-written macro.

pub use solana_account_view::{
    AccountView, RuntimeAccount, MAX_PERMITTED_DATA_INCREASE, NOT_BORROWED,
};

#[macro_export]
/// Installs an allocator that rejects every allocation request.
macro_rules! no_alloc {
    () => {
        pub mod allocator {
            extern crate alloc;
            pub struct NoAlloc;
            // SAFETY: `alloc` always aborts and never returns memory, while
            // `dealloc` is a no-op because no allocation can succeed.
            unsafe impl alloc::alloc::GlobalAlloc for NoAlloc {
                #[inline]
                unsafe fn alloc(&self, _: core::alloc::Layout) -> *mut u8 {
                    $crate::abort_program()
                }
                #[inline]
                unsafe fn dealloc(&self, _: *mut u8, _: core::alloc::Layout) {}
            }

            #[cfg(any(target_os = "solana", target_arch = "bpf"))]
            #[global_allocator]
            static A: NoAlloc = NoAlloc;
        }
    };
}

#[macro_export]
/// Installs the SBF panic handler that aborts the current program.
macro_rules! panic_handler {
    () => {
        #[cfg(any(target_os = "solana", target_arch = "bpf"))]
        #[panic_handler]
        fn panic(_info: &core::panic::PanicInfo<'_>) -> ! {
            $crate::abort_program()
        }
    };
}

/// The bump allocator used as the default Rust heap when running programs.
#[macro_export]
macro_rules! heap_alloc {
    () => {
        pub mod allocator {
            extern crate alloc;

            /// Maximum heap length in bytes that a program can request.
            pub const MAX_HEAP_LENGTH: u32 = 256 * 1024; // 256 KiB
            /// Start address of the memory region used for program heap.
            pub const HEAP_START_ADDRESS: u64 = 0x300000000;

            /// Cursor value that causes the next allocation to fail cleanly.
            ///
            /// Used by `#[instruction(heap)]` codegen to trap allocations on
            /// non-heap endpoints. Setting the cursor to `HEAP_START + MAX_HEAP`
            /// means the next `alloc()` will see `self.end < end` and return null,
            /// which the global allocator converts to an abort.
            pub const HEAP_CURSOR_POISONED: usize =
                HEAP_START_ADDRESS as usize + MAX_HEAP_LENGTH as usize;

            pub struct BumpAllocator {
                start: usize,
                end: usize,
            }
            impl BumpAllocator {
                /// # Safety
                ///
                /// `start..start + len` must describe the SVM heap region, and
                /// `start` must point to the heap cursor word.
                pub const unsafe fn new_unchecked(start: usize, len: usize) -> Self {
                    Self {
                        start,
                        end: start + len,
                    }
                }
            }

            /// # Safety
            ///
            /// - `self.start` must point to a valid heap cursor (usize at heap start).
            /// - The SVM zero-inits the heap region and the entrypoint writes the
            ///   initial cursor value before any allocation.
            /// - Re-entrancy is forbidden by the SVM, so no aliasing can occur.
            /// - `alloc_zeroed` delegates to `alloc` because the SVM heap is
            ///   pre-zeroed.
            /// - `dealloc` is a no-op; bump allocators do not free individual
            ///   allocations.
            #[allow(clippy::arithmetic_side_effects)]
            unsafe impl alloc::alloc::GlobalAlloc for BumpAllocator {
                #[inline]
                unsafe fn alloc(&self, layout: core::alloc::Layout) -> *mut u8 {
                    let pos_ptr = self.start as *mut usize;
                    // SAFETY: `new_unchecked` was called with the SVM heap
                    // cursor address.
                    let pos = unsafe { *pos_ptr };

                    let allocation = (pos.wrapping_add(layout.align() - 1)) & !(layout.align() - 1);

                    // Overflow guard: any request > 256 KiB cannot succeed and prevents
                    // allocation + layout.size() from wrapping usize.
                    let end = allocation.wrapping_add(layout.size());
                    if $crate::utils::hint::unlikely(layout.size() > MAX_HEAP_LENGTH as usize)
                        || $crate::utils::hint::unlikely(self.end < end)
                    {
                        return core::ptr::null_mut();
                    }

                    // SAFETY: Same heap cursor pointer as above; allocator has
                    // exclusive access during the instruction.
                    unsafe { *pos_ptr = end };
                    allocation as *mut u8
                }

                #[inline]
                unsafe fn alloc_zeroed(&self, layout: core::alloc::Layout) -> *mut u8 {
                    // SAFETY: Same requirements as `alloc`; the SVM heap is
                    // already zeroed.
                    unsafe { self.alloc(layout) }
                }

                #[inline]
                unsafe fn dealloc(&self, _: *mut u8, _: core::alloc::Layout) {}
            }

            #[cfg(any(target_os = "solana", target_arch = "bpf"))]
            #[global_allocator]
            // SAFETY: These constants describe the SVM heap region.
            static A: BumpAllocator = unsafe {
                BumpAllocator::new_unchecked(HEAP_START_ADDRESS as usize, MAX_HEAP_LENGTH as usize)
            };
        }
    };
}
